;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        esprit/beginning-of-line
        org-delete-char
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        straight-remove-unused-repos
        ))
