;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        esprit/beginning-of-line
        exit-recursive-edit
        indent-for-tab-command
        keyboard-escape-quit
        org-delete-char
        org-self-insert-command
        org-yank
        ))

(setq mc/cmds-to-run-once
      '(
        consult-yank-pop
        dabbrev-completion
        end-of-buffer
        end-of-visual-line
        straight-remove-unused-repos
        ))
