#+TITLE: Emacs Literate Configuration
#+AUTHOR: Luke D. Inglis
#+DATE: 11/2023
#+STARTUP: show2levels indent hidestars
#+PROPERTY: header-args :tangle (let ((org-use-tag-inheritance t)) (if (member "INACTIVE" (org-get-tags))  "no" "~/code/dotemacs/init.el")))

* Emacs Literate Configuration
* Documentation
** Forwards

While learning Emacs I've tried a lot of different prepackaged 'distros'. Most notably, as an erstwhile (neo)vim user, Doom. After learning enough via that route and additionally deciding to try to give vanilla Emacs a solid try I'm leaving the prepackaged distros behind and building my own configuration.

It won't be 100% from scratch (are they ever?) as I really like the approach of the NΛNO configuration project and have built from that. Over all I aim for a practically minimalist approach. 

Naturally my config is built 'on the shoulders of giants' where much more experienced Emacs users have gone before. With the goal of learning in mind I aim to do my best to not put anything in this config unless I understand how it works.

To wit, giants on whose shoulders I stand. In no particular order.

+ [[https://github.com/rememberYou/.emacs.d][Terencio Agozzino]] (=rememberYou=)
+ [[https://github.com/rougier/dotemacs][Nicolas Rougier (rougier) - Author of NANO]]
+ [[https://github.com/daviwil/dotfiles/blob/master/Emacs.org][David Wilson (daviwil) - System Crafter]]

Big thanks to those from whom I have learned. (And copy and pasted from...)

As this config sprouted originally from N. Rougier's I will quote directly part of the preamble to his.

#+begin_quote

This document is a literate configuration for GNU Emacs written in [[https://orgmode.org/][org]] format. It cannot be used directly and needs to be transformed to extract all the different code blocks into a single configuration file. This is done using the [[help:org-babel-tangle][org-babel-tangle]] function that "extract the bodies of all source code blocks from the current file into their own source-specific files". You can try by yourself by typing the sequence: =C-c C-v t= (org-babel-execute-subtree).

#+end_quote

ToDo [1/6]                                                    :INACTIVE:

- [ ] Change underlying Coreutils on MacOS to be the GNU version and adjust config accordingly if necessary.
- [ ] Extract the non-theme related settings from the =liminal-mode= settings
- [X] Switch to my own fork of the modeline
- [ ] Investigate [[https://github.com/mickeynp/combobulate][Combobulate]] as an alternative to Objed
- [ ] Try [[https://github.com/radian-software/prescient.el][prescient]] for completion sorting and filtering
- [ ] Try out Embark. Looks super cool. Maybe able to combine with Objed or Combobulate.

* Core
** Header 

This will generate a header at the top of the tangled file to indicate it is generated and is not meant to be modified directly.

#+begin_src emacs-lisp :epilogue (format-time-string ";; Last generated on %c")

  ;;; dotemacs --- A literate Emacs configuration -*- lexical-binding: t -*-
  ;;; This file has been generated from dotemacs.org file. DO NOT EDIT.

  ;;; Copyright (C) 2024 Luke D. Inglis

  ;;; This file is free software; you can redistribute it and/or modify
  ;;; it under the terms of the GNU General Public License as published by
  ;;; the Free Software Foundation; either version 3, or (at your option)
  ;;; any later version.

  ;;; This file is distributed in the hope that it will be useful,
  ;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
  ;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ;;; GNU General Public License for more details.

  ;;; For a full copy of the GNU General Public License
  ;;; see <https://www.gnu.org/licenses/>.

  ;;; Code

#+end_src

** Early Init                                                   :HOOK:OTHER:
:PROPERTIES:
:header-args:emacs-lisp: :tangle ~/code/dotemacs/early-init.el
:END:

This code is meant to go to the [[file:early-init.el][early-init.el]] file.

#+begin_src emacs-lisp

  (setq
   site-run-file nil                         ; No site-wide run-time initializations.
   inhibit-default-init t                    ; No site-wide default library
   gc-cons-threshold most-positive-fixnum    ; Very large threshold for garbage
                                             ; collector during init
   package-enable-at-startup nil)            ; We'll use straight.el

  (setq native-comp-eln-load-path
        (list (expand-file-name "eln-cache" user-emacs-directory)))

  ;; Reset garbage collector limit after init process has ended (8Mo)
  (add-hook 'after-init-hook
            #'(lambda () (setq gc-cons-threshold (* 8 1024 1024))))

#+end_src

** Packages management                                            :PERSONAL:

Using [[https://github.com/raxod502/straight.el][straight.el]] for package management and disable checking (for speedup). Hook it up to =use-package= by default at least for the time being.

#+begin_src emacs-lisp

  (unless (featurep 'straight)
    ;; Bootstrap straight.el
    (defvar bootstrap-version)
    (let ((bootstrap-file
           (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
          (bootstrap-version 5))
      (unless (file-exists-p bootstrap-file)
        (with-current-buffer
            (url-retrieve-synchronously
             "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
             'silent 'inhibit-cookies)
          (goto-char (point-max))
          (eval-print-last-sexp)))
      (load bootstrap-file nil 'nomessage)))

  (setq straight-check-for-modifications nil)
  
  #+end_src

  Library load paths with a special case for mu4e (you may need to adapt this path).

  #+begin_src emacs-lisp

    (add-to-list 'load-path
                 (expand-file-name "lisp" user-emacs-directory))

  #+end_src

** Packages installation

Packages used in this specific configuration. You may want to adapt this list. The first time this sequence will be executed, *it will take a long time*. Then, at next restart, it should be very fast (less than 1 second because it won't install anything basically).

#+begin_src emacs-lisp

  (setq package-list
        '(
          avy                  ; Jump to things (but really much, much more...)
          cape                 ; Completion At Point Extensions
          charmap              ; Explorable Unicode table
          circadian            ; Change my theme in rhythm with nature
          coffee-mode          ; Sadly still have to deal with coffeescript sometimes
          consult              ; Consulting completing-read
          consult-lsp          ; LSP extras for consult to, well, consult
          corfu                ; Completion Overlay Region FUnction
          deft                 ; Enhanced note taking with Org
          embark
          embark-consult
          exec-path-from-shell ; Get environment variables such as $PATH from the shell
          f                    ; Modern API for working with files and directories
          flycheck             ; Enhanced syntax checking, more flexible than flymake
          flycheck-eglot       ; Allow Flycheck to understand Eglot as a checker
          haml-mode            ; Rails templates not covered by treesitter or web-mode
          helpful              ; A better help buffer
          imenu-list           ; Show imenu entries in a separate
          language-id
          lua-mode
          magit                ; A Git porcelain inside Emacs.
          marginalia           ; Enrich existing commands with completion annotations
          markdown-mode        ; Major mode for Markdown-formatted text
          no-littering         ; Keep our things clean and tidy
          orderless            ; Completion style for matching regexps in any order
          org-auto-tangle
          projectile           ; Project scoped stuffness
          rainbow-mode         ; Sometime you just need to see the colors
          rg                   ; Ripgrep for speed and profit(?)
          slim-mode
          smartscan            ; A little package to quick hop to 
          smartparens          ; Like parens but, you know, ...smarter
          tempel               ; A tiny template package. Emacs' venerable Tempo for a new age
          tempel-collection    ; A young and growing collection of templates for Tempel
          transpose-frame
          treesit-auto
          undo-fu              ; Work around Emacs' clunky undo interface
          undo-fu-session      ; Persistant undo across sessions
          vertico              ; VERTical Interactive COmpletion
          vertico-posframe
          visual-fill-column   ; Nicer wrapping mostly for text modes
          vterm                ; A real terminal emulator running in Emacs
          web-mode             ; Uber mode for web templating languages
          which-key            ; Discovery method for key bindings
          zetteldeft           ; Put your deft notes in little slip boxen
          ))

  ;; Install packages that are not yet installed
  (dolist (package package-list)
    (straight-use-package package))

  ;; Install a selection of the N Λ N O suite of packages install straight from GitHub

  ;; A cleaner, more minimal Org agenda
  (straight-use-package
   '(nano-agenda :type git :host github :repo "rougier/nano-agenda"))

  (straight-use-package
   '(jtsx :type git :host github :repo "llemaitre19/jtsx"))

  ;; (straight-use-package
  ;;  '(liminal-theme :local-repo "~/code/liminal-theme"))

  ;; ;; Modeline (eventually to be replace with my own)
  ;; (straight-use-package
  ;;  '(liminal-modeline :local-repo "~/code/liminal-modeline"))

  (straight-use-package
   '(asdf :type git :host github :repo "tabfugnic/asdf.el"))

  (straight-use-package
   '(eglot-ltex :type git :host github :repo "emacs-languagetool/eglot-ltex"))

  (straight-use-package '(org :type built-in))

  #+end_src

** Meta-Configuration

Setup and tooling specifically related to this configuration itself.

*** Init time

Display a message to the *Messages* buffer showing the Emacs init time.

#+begin_src emacs-lisp

  (let ((inhibit-message t))
    (message "Welcome to GNU Emacs / Liminal edition")
    (message (format "Initialization time: %s" (emacs-init-time))))

#+end_src

*** Configuration reload

#+begin_src emacs-lisp

  (defun reload-init-file ()
    "Reload the file referenced by `user-init-file`."

    (interactive)
    (load-file user-init-file))

  (global-set-key (kbd "<f5>") 'reload-init-file)

#+end_src

*** Auto-tangle

Automatically tangle org-mode files with the option #+auto_tangle: t

#+begin_src emacs-lisp

  (add-hook 'org-mode-hook 'org-auto-tangle-mode)

#+end_src

** Backups Etc.

=no-littering= below takes care of some of this type of stuff automatically but still fix things up before invoking that.

#+begin_src emacs-lisp

  (setq vc-make-backup-files nil     ; No backup of files under version contr
        backup-by-copying t          ; Don't clobber symlinks
        version-control t            ; Version numbers for backup files
        delete-old-versions t        ; Delete excess backup files silently
        kept-old-versions 3          ; Number of old versions to keep
        kept-new-versions 6          ; Number of new versions to keep
        delete-by-moving-to-trash t  ; Delete files to trash
        create-lockfiles nil)        ; More trouble than worth

#+end_src

Use [[https://github.com/emacscollective/no-littering][no-littering]] to keep my config directory tidier. Configured using the settings advised by [[https://rossabaker.com/configs/emacs/][Ross A. Baker]].

#+begin_src emacs-lisp

  (use-package no-littering
    :init
    (setq no-littering-etc-directory "~/.cache/emacs/etc/"
          no-littering-var-directory "~/.cache/emacs/var/")
    (when (fboundp 'startup-redirect-eln-cache)
      (startup-redirect-eln-cache
       (convert-standard-filename
        (expand-file-name  "eln-cache/" no-littering-var-directory))))
    :config
    (setq
     backup-directory-alist
     `((".*" . ,(no-littering-expand-var-file-name "backup/")))
     auto-save-file-name-transforms
     `((".*" ,(no-littering-expand-var-file-name "auto-save/") t))))

#+end_src

** History :HOOK:

Remove text properties for kill ring entries (see https://emacs.stackexchange.com/questions/4187). This saves a lot of time when loading it.

 #+begin_src emacs-lisp 

(defun unpropertize-kill-ring ()
  (setq kill-ring (mapcar 'substring-no-properties kill-ring)))

(add-hook 'kill-emacs-hook 'unpropertize-kill-ring)

#+end_src

We save every possible history we can think of.

#+begin_src emacs-lisp 

(require 'savehist)

(setq kill-ring-max 50
      history-length 50)

(setq savehist-additional-variables
      '(kill-ring
        command-history
        set-variable-value-history
        custom-variable-history   
        query-replace-history     
        read-expression-history   
        minibuffer-history        
        read-char-history         
        face-name-history         
        bookmark-history
        file-name-history))

 (put 'minibuffer-history         'history-length 50)
 (put 'file-name-history          'history-length 50)
 (put 'set-variable-value-history 'history-length 25)
 (put 'custom-variable-history    'history-length 25)
 (put 'query-replace-history      'history-length 25)
 (put 'read-expression-history    'history-length 25)
 (put 'read-char-history          'history-length 25)
 (put 'face-name-history          'history-length 25)
 (put 'bookmark-history           'history-length 25)

#+end_src

No duplicates in history
  
#+begin_src emacs-lisp

(setq history-delete-duplicates t)

#+end_src
  
Start history mode.

#+begin_src emacs-lisp

(let (message-log-max)
  (savehist-mode))

#+end_src

** Path

Pull my full set of environmental variables into Emacs. This is most important on MacOS where I am currently spending all of my time.

#+begin_src emacs-lisp

  (use-package exec-path-from-shell
    :init
    (exec-path-from-shell-initialize))

#+end_src

Make Emacs aware of the proper paths for the [[https://asdf-vm.com/][asdf version manager]].

#+begin_src emacs-lisp

  (use-package asdf
    :config
    (asdf-enable))

#+end_src

point to my local root directory. Mostly for the sake of Org later on in the config.

#+begin_src emacs-lisp

  (setq luda/local-root "~/")

#+end_src

** MacOS specific settings

Juggle a few modifier keys to make things a little more comfortable. Tell dired not to use the underlying =ls= command on Mac since it doesn't use GNUVC oreutils which is what dired expects.

#+begin_src emacs-lisp

  (when (string-equal system-type "darwin")
    (setq mac-option-modifier 'super)
    (setq mac-command-modifier 'meta)
    (setq dired-use-ls-dired nil))

#+end_src

** Server

In theory the server should be running via a Homebrew installed Plist via =launchctl=. However, if it isn't running already than start it when Emacs is initialized.

#+begin_src emacs-lisp

  (require 'server)

  (unless (server-running-p)
    (start-server))

#+end_src

* Frame

A variation on =make-frame= that opens to the =*scratch*= buffer rather than the current buffer.

#+begin_src emacs-lisp

  (defun luda/make-scratch-frame ()
    "Create a new frame and switch to *scratch* buffer."

    (interactive)
    (select-frame (make-frame))
    (switch-to-buffer "*scratch*"))

  (defvar-keymap liminal-new-frame-map
    :doc "Liminal prefix map for creating frames."
    "c" #'make-frame
    "s" #'luda/make-scratch-frame)

  (defvar-keymap liminal-frame-map
    :doc "Liminal prefix key maps for frames."
    "n" liminal-new-frame-map)

  (keymap-set global-map "M-n" liminal-frame-map)

#+end_src

Frame/window navigation bindings

#+begin_src emacs-lisp

  (global-set-key (kbd "M-o") 'other-window)
  (global-set-key (kbd "s-o") 'other-frame)

#+end_src

* Visual
** Liminal Theme

My version of the =nano-theme= package. Currently it's a straightforward fork with mostly just the colors changed and the nano naming replaced with my own liminal naming.

Visually a lot of what I'm going for is derived from the N Λ N O project and things found in its author personal config. I'm currently in the process of forking and customizing various aspects of it.

As part of it's setup it is running the =liminal-mode= function which sets a number of sensible defaults and settings. For me it would make more sense for these to be there own separate setup but I haven't extracted them yet.

#+begin_src emacs-lisp

  (use-package liminal-theme
    :load-path "~/code/liminal-theme"
    :init
    (setopt liminal-manage-cursor t
            liminal-manage-fonts t
            liminal-manage-ui t
            liminal-manage-ux t
            liminal-font-size 18)
    :config
    (liminal-mode))

#+end_src
** Liminal Mode

The =nano-theme= package on which my Liminal theme is based has a =liminal-mode= function which sets a number of variables settings to make Emacs conform to Rougier's presentation goals. While I like most of his choices I don't necessarily think all of the settings would be set by the theme itself. Here I'm extracting them. 

** N Λ N O modeline

I like the idea and the behavior of this modeline but there are a few more things that I would have present that are missing from it. I have forked it but haven't made any useful changes made.

#+begin_src emacs-lisp

  (use-package liminal-modeline
    :after liminal-theme
    :load-path "~/code/liminal-modeline"
    :init
    (setopt mode-line-format nil)
    :hook
    (prog-mode            . liminal-modeline-prog-mode)
    (text-mode            . liminal-modeline-text-mode)
    (org-mode             . liminal-modeline-org-mode)
    (term-mode            . liminal-modeline-term-mode)
    (vterm-mode           . liminal-modeline-term-mode)
    (messages-buffer-mode . liminal-modeline-message-mode)
    (org-capture-mode     . liminal-modeline-org-capture-mode)
    (org-agenda-mode      . liminal-modeline-org-agenda-mode))

#+end_src

** Circadian

I prefer the legibility of a well designed light theme when the lighting is good. However, I don't want to burn my retinas at night. Thankfully =circadian= exists to automatically adjust my theme at sunrise/sunset in my local area.

#+begin_src emacs-lisp

  (use-package circadian
    :custom
     (calendar-latitude 42.4)
     (calendar-longitude -71.0)
     (circadian-themes '((:sunrise . liminal-light)
                         (:sunset  . liminal-dark)))
     :config
     (circadian-setup))

#+end_src

** Miscellaneous visual settings.

Nicer display of text lines visually.

#+begin_src emacs-lisp

  (setq-default line-spacing 1)
  (global-visual-line-mode)

#+end_src

Always waffle on how minimal to be. Right now line numbers in prog modes are useful enough to allow within my minimal aesthetic.

#+begin_src emacs-lisp

  (use-package display-line-numbers
    :custom
    (display-line-numbers-widen t)
    :hook
    ((prog-mode conf-mode) . display-line-numbers-mode))

#+end_src

* Completion
*** Vertico

Building on Emacs own =completing-read= function Vertico provides a minimalist UI for completion in the minibuffer. It can be thought of as a sleeker, more minimalist alternative to [[https://github.com/abo-abo/swiper][Ivy]] or [[https://github.com/emacs-helm/helm][Helm]]. 

#+begin_src emacs-lisp

  (use-package vertico
    :bind (:map vertico-map
                ("C-<backspace>" . vertico-directory-up))
    :custom
    (vertico-scroll-margin 0 "Remove the top/bottom margins of the completion window")
    (vertico-resize t "Let the completion window grow and shrink")
    (vertico-multiform-categories ; Choose a multiform
     '((file reverse)
       (consult-location)
       (imenu buffer)
       (library reverse indexed)
       (org-roam-node reverse indexed)
       (t reverse)
       ))
    (vertico-multiform-commands
     '(("flyspell-correct-*" grid reverse)
       (org-refile grid reverse indexed)
       (consult-yank-pop indexed)
       (consult-flycheck)
       (consult-lsp-diagnostics)
       ))
    :init
    (vertico-mode))

#+end_src

*** Consult

What Vertico is to Ivy [[https://github.com/minad/consult][Consult]] is to Ivy's =counsel-mode=. It provides searchable replacements to many common Emacs commands.

#+begin_src emacs-lisp

  (defun wrapper/consult-ripgrep (&optional dir given-initial)
    "Pass the region to consult-ripgrep if available.

  DIR and GIVEN-INITIAL match the method signature of `consult-wrapper'."
    (interactive "P")
    (let ((initial
           (or given-initial
               (when (use-region-p)
                 (buffer-substring-no-properties (region-beginning) (region-end))))))
      (consult-ripgrep dir initial)))

  (use-package consult
    :config
    (recentf-mode)
    :bind (
           ("M-s d" . consult-find)                  ;; Alternative: consult-fd
           ("M-s c" . consult-locate)
           ("M-s g" . consult-grep)
           ("M-s G" . consult-git-grep)
           ("M-s r" . wrapper/consult-ripgrep)
           ("M-s l" . consult-line)
           ("M-s L" . consult-line-multi)
           ("M-s k" . consult-keep-lines)
           ("M-s u" . consult-focus-lines)
           ("M-x"   . consult-buffer)
           ("M-y"   . consult-nk-pop)
           ("M-g g" . consult-goto-line)
           ("M-g i" . consult-imenu)
           ("M-g o" . consult-outline)
           ("C-x b" . consult-bookmark)))

#+end_src

*** Orderless

Orderless enhances completion functions allowing for searching by space delimited terms. The order of these terms does not matter, hence the name.

#+begin_src emacs-lisp

  (use-package orderless
    :config
     (setq completion-styles '(orderless partial-completion basic))
     (setq completion-category-defaults nil)
     (setq completion-category-overrides '((file (styles partial-completion)))))

#+end_src

*** Tempel                                                       :INACTIVE:

Tempel is a /"Tempel is a tiny template package for Emacs"/ from Minad (that wizard of Emacs packages). It takes much of its inspiration and its template syntax from the venerable old =Tempo= library.

#+begin_src emacs-lisp

  ;; Configure Tempel
  (use-package tempel
    ;; Require trigger prefix before template name when completing.
    :custom
    (tempel-trigger-prefix "<"))

  ;; Optional: Add tempel-collection.
  ;; The package is young and doesn't have comprehensive coverage.
  (use-package tempel-collection
    :after tempel)

#+end_src

*** Corfu

Another package from =minad= (author of Vertico and Consult) Corfu is the 'in-buffer completion counterpart' to Vertico. Similarly it provides a minimalist wrapper around native bahaviors to provide an enhanced experience. Corfu hooks into Emacs' native =complete-in-region= and leverages whatever sources are available from =completion-at-point-functions= as sources for completion options.

#+begin_src emacs-lisp

  (use-package corfu
    :config
    (defun corfu-x-eshell-hook ()
      (setq-local corfu-auto nil)
      (corfu-mode))
    (add-hook 'eshell-mode-hook 'corfu-x-eshell-hook)
    (setq corfu-cycle t
          corfu-popupinfo-delay '(1.0 . 0.5)
          corfu-preview-current 'insert
          corfu-on-exact-match 'insert)
    :bind
    (:map corfu-map
          ("SPC" . corfu-insert-separator)
          ("C-n" . corfu-next)
          ("C-p" . corfu-previous)
          ("TAB" . corfu-insert)
          ("RET" . nil))
    :init
    (corfu-popupinfo-mode)
    (corfu-history-mode)
    (global-corfu-mode))

  #+end_src

*** Cape

Yet another package from =minad=. As mentioned Corfu leverages the =completion-at-point-functions= to populate its options. Cape complements it by providing a suite of such functions, usually referred to as Capfs.

#+begin_src emacs-lisp

  (use-package cape
    :bind
    (("C-c f" .  cape-file))

    :config
    ;; Add `completion-at-point-functions', used by `completion-at-point'.
    (defalias 'dabbrev-after-2 (cape-capf-prefix-length #'cape-dabbrev 2))
    (add-to-list 'completion-at-point-functions 'dabbrev-after-2 t)

    (cl-pushnew #'cape-file completion-at-point-functions)

    ;; Add to the global default value of `completion-at-point-functions' which is
    ;; used by `completion-at-point'.  The order of the functions matters, the
    ;; first function returning a result wins.  Note that the list of buffer-local
    ;; completion functions takes precedence over the global list.

    (add-to-list 'completion-at-point-functions #'cape-dabbrev)
    (add-to-list 'completion-at-point-functions #'cape-file)
    (add-to-list 'completion-at-point-functions #'cape-elisp-block)
    (add-to-list 'completion-at-point-functions #'cape-dict)

    ;; Silence then pcomplete capf, no errors or messages!
    (advice-add 'pcomplete-completions-at-point :around #'cape-wrap-silent)

    ;; Ensure that pcomplete does not write to the buffer
    ;; and behaves as a pure `completion-at-point-function'.
    (advice-add 'pcomplete-completions-at-point :around #'cape-wrap-purify)
    ;; Bust the Corfu completion cache when using Eglot to ensure fresh completions
    (advice-add 'eglot-completion-at-point :around #'cape-wrap-buster))

#+end_src

*** Marginalia

Marginalia adds rich annotations to the minibuffer completions. Good for quick reference and discoverability.

#+begin_src emacs-lisp

  (use-package marginalia
    :init
    (marginalia-mode)
    :bind (:map minibuffer-local-map
                ("M-A" . marginalia-cycle)))

#+end_src

*** Embark

#+begin_src emacs-lisp

  (use-package embark
    :bind
    (("C-." . embark-act)         ;; pick some comfortable binding
     ("M-." . embark-dwim)        ;; good alternative: M-.
     ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'

    :init

    ;; Optionally replace the key help with a completing-read interface
    (setq prefix-help-command #'embark-prefix-help-command)

    ;; Show the Embark target at point via Eldoc. You may adjust the
    ;; Eldoc strategy, if you want to see the documentation from
    ;; multiple providers. Beware that using this can be a little
    ;; jarring since the message shown in the minibuffer can be more
    ;; than one line, causing the modeline to move up and down:

    ;; (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
    ;; (setq eldoc-documentation-strategy #'eldoc-documentation-compose-eagerly)

    :config

    ;; Hide the mode line of the Embark live/completions buffers
    (add-to-list 'display-buffer-alist
                 '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                   nil
                   (window-parameters (mode-line-format . none)))))

  ;; Consult users will also want the embark-consult package.
  (use-package embark-consult
    :hook
    (embark-collect-mode . consult-preview-at-point-mode))

#+end_src

* Minibuffer

#+begin_src emacs-lisp

  ;; Add prompt indicator to `completing-read-multiple'.
  ;; We display [CRM<separator>], e.g., [CRM,] if the separator is a comma.
  (defun crm-indicator (args)
    (cons (format "[CRM%s] %s"
                  (replace-regexp-in-string
                   "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
                   crm-separator)
                  (car args))
          (cdr args)))
  (advice-add #'completing-read-multiple :filter-args #'crm-indicator)

  ;; Do not allow the cursor in the minibuffer prompt
  (setq minibuffer-prompt-properties
        '(read-only t cursor-intangible t face minibuffer-prompt))
  (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)

  ;; Emacs 28: Hide commands in M-x which do not work in the current mode.
  ;; Vertico commands are hidden in normal buffers.
  (setq read-extended-command-predicate #'command-completion-default-include-p)

  ;; Enable recursive minibuffers
  (setq enable-recursive-minibuffers t)

#+end_src

* Which key for discoverability

Add =which-key= for discoverability and because I can only ever remember my most used key bindings.

#+begin_src emacs-lisp

  (use-package which-key
    :config
    (setq which-key-idle-delay 0.75)
    (which-key-mode))

#+end_src

* LSP

Use Eglot for LSP integration. Fewer options than =lsp-mode= but it's built-in and covers the ground that I need it for right noe

#+begin_src emacs-lisp

  (defun luda/eglot-capf ()
    (setq-local completion-at-point-functions
                (list (cape-capf-super
                       #'eglot-completion-at-point
                       #'cape-file))))

  (use-package eglot
    :bind (:map eglot-mode-map
                ("C-x l r" . eglot-rename))
    ;; ("M-k" . eglot-code-actions)
    :hook ((eglot-managed-mode . luda/eglot-capf)
           (ruby-ts-mode . eglot-ensure)
           (jsx-mode . eglot-ensure)
           (css-mode . eglot-ensure)
           (org-mode . eglot-ensure))
    :config
    (setq eldoc-echo-area-use-multiline-p nil)
    (add-to-list 'eglot-server-programs
                 '(ruby-base-mode . ("solargraph" "stdio")))
    (add-to-list 'eglot-server-programs
                 '(org-mode . ("efm-langserver"))))


#+end_src

#+begin_src emacs-lisp

  (use-package eglot-ltex
    :hook (text-mode . (lambda ()
                         (require 'eglot-ltex)
                         (eglot-ensure)))
    :init
    (setq eglot-ltex-server-path "/usr/local/bin/ltex-ls"
          eglot-ltex-communication-channel 'stdio))

#+end_src
* Code analysis
** Flycheck

Flycheck to run checkers, linters, etc. Also hook Flycheck and Eglot together so that errors, warnings. etc. returned from language servers are piped through Flycheck.

#+begin_src emacs-lisp

  (use-package flycheck
    :config
    (global-flycheck-mode))

  (use-package flycheck-eglot
    :config
    (global-flycheck-eglot-mode)
    :after (flycheck eglot))

#+end_src

** Flyspell                                                       :INACTIVE:

Another Fly, this time Flyspell. Spellchecking everywhere/everywhen because I am dyslexic and I type quickly. Add my own =save-word= function as I use a fair number of domain terms etc. that aren't in general purpose dictionaries.

#+begin_src emacs-lisp

  (defun luda/save-word ()
    "Mark a Flyspell reported error as acceptable."

    (interactive)

    (let ((current-location (point))
          (word (flyspell-get-word)))
      (when (consp word)
        (flyspell-do-correct 'save nil (car word) current-location (cadr word) (caddr word) current-location))))

  (use-package flyspell
    :bind
     ("C-x $" . 'luda/save-word)
     ("C-'" . 'flyspell-auto-correct-previous-word)
    :hook ((text-mode . flyspell-mode)
           (prog-mode . flyspell-prog-mode))
    :config
    ;; Configure `LANG`, otherwise ispell.el cannot find a 'default
    ;; dictionary' even though multiple dictionaries will be configured
    ;; in next line.
    
    (setenv "LANG" "en_US.UTF-8")
    (setq ispell-program-name "hunspell")
    ;; Configure German, Swiss German, and two variants of English.
    (setq ispell-dictionary "en_US,en_CA,fr_FR")
    ;; ispell-set-spellchecker-params has to be called
    ;; before ispell-hunspell-add-multi-dic will work
    (ispell-set-spellchecker-params)
    (ispell-hunspell-add-multi-dic "en_US,en_CA,fr_FR")
    ;; For saving words to the personal dictionary, don't infer it from
    ;; the locale, otherwise it would save to ~/.hunspell_de_DE.
    (setq ispell-personal-dictionary "~/.hunspell_personal"))

#+end_src

* Treesitter
:PROPERTIES:
:ID:       6C614835-66FB-4D2D-A1E9-B1042C786694
:END:

I tried the =treesit-auto= package for automagically handling installation and activation of Treesitter parsers/modes but it wasn't working as smoothly as I'd hoped so I'm going to just handle things manually for the time being.

Edit: trying =treesit-auto= yet again as I was unable to get /anything/ to work smoothly/right.

#+begin_src emacs-lisp

  (setq treesit-language-source-alist
        '((css "https://github.com/tree-sitter/tree-sitter-css")
          (lua "https://github.com/MunifTanjim/tree-sitter-lua")
          (ruby "https://github.com/tree-sitter/tree-sitter-ruby")
          (dockerfile "https://github.com/camdencheek/tree-sitter-dockerfile")
          (scss "https://github.com/serenadeai/tree-sitter-scss")
          (elisp "https://github.com/Wilfred/tree-sitter-elisp")
          (go "https://github.com/tree-sitter/tree-sitter-go")
          (html "https://github.com/tree-sitter/tree-sitter-html")
          (json "https://github.com/tree-sitter/tree-sitter-json")
          (make "https://github.com/alemuller/tree-sitter-make")
          (markdown "https://github.com/ikatyang/tree-sitter-markdown")
          (toml "https://github.com/tree-sitter/tree-sitter-toml")
          (yaml "https://github.com/ikatyang/tree-sitter-yaml")))

  (dolist (ts-pair treesit-language-source-alist)
    (let ((language (car ts-pair)) (repo (cadr ts-pair)))
      (unless (treesit-language-available-p language)
        (message "Installing parser for %s from %s" language repo)
        (treesit-install-language-grammar language))))

  (use-package treesit-auto
    :custom
    (treesit-auto-install 'prompt)
    :config
    (global-treesit-auto-mode))

#+end_src

* Projectile

The de facto standard for project scoped actions bring in =projectile= with no additional customization.

#+begin_src emacs-lisp

  (use-package projectile
    :config
    (projectile-global-mode)
    :bind
    ("s-p" . projectile-command-map)
    ("C-c p" . projectile-command-map))

#+end_src

* Text editing and navigation

For a very long time I was a Vim/Neovim user. I love Vim but I've really gotten absorbed into the world of Emacs. Neovim in particular feels like a great tool to use but Emacs feels more like an extension of my brain. I'm pretty all in at this point.

However, there are a few things that I really miss about the Vim and the plugins I used in my setup. Some are bigger than others.

** Avy

Just looking at the tin [[https://github.com/abo-abo/avy][Avy]] is a /...package for jumping to visible text using a char-based decision tree./ However, as Karthik Chikmagalur puts it /Avy can do any thing/.

I'm taking his lead and trying it out as the power tools he makes it out to be.

#+begin_src emacs-lisp

  (use-package avy
    :bind ("M-j" . avy-goto-char-timer))

#+end_src

** Occur

Yet another builtin I'm slowly learning to make the most of.

#+begin_src emacs-lisp

  (use-package occur
    :bind (:map isearch-mode-map ("C-o" . isearch-occur)))

#+end_src

** Surround

Vim itself has some handy built in commands for dealing with surrounding elements. There are several lovely plugins for extending that behavior. Emacs is lacking in this department. At least as far as I can tell. So bring in =surround.el= which is relatively new and behaves much like the plugins I'm used to from Neovim.

Being new it has some rough edges but I like it. Maybe I'll try to pitch in and fix some of the issues I have.

#+begin_src emacs-lisp

  (use-package surround
    :bind-keymap
    ("M-'" . surround-keymap))

#+end_src

** Objed

I haven't missed modal Vim's modal editing as much as I thought I might when I switched to vanilla Emacs. What I do miss is the concept of /text objects/. They are such a natural way of thinking about things for me that I needed a way to bring that idea into Emacs in an intuitive feeling way. Thankfully =objed-mode= exists. It has some rough edges I haven't worked around yet but it does the job quite well for now.

#+begin_src emacs-lisp

  (use-package objed
    :load-path "~/code/objed"
    :config
    (setq objed-modeline-hint nil)
    (objed-mode)
    :bind
    ("M-SPC" . objed-activate-object))

#+end_src

** Multiple Cursors

Having multiple cursors is an interesting enough approach that I'm playing
around with it to see if I can make it fit into my workflow. There might be way
to accomplish similar behavior with something like Objed this not having to add
multiple packages but for the time being I'll see if the actual
=multiple=cursors= package does the trick.

#+begin_src emacs-lisp

  (use-package multiple-cursors
    :bind (("C-M-SPC" . set-rectangular-region-anchor)
           ("C->" . mc/mark-next-like-this)
           ("C-<" . mc/mark-previous-like-this)
           ("C-c C->" . mc/mark-all-like-this)
           ("C-c C-SPC" . mc/edit-lines)))

#+end_src

** Regexen + Search and replace
:PROPERTIES:
:ID:       1739F061-BA7D-4A55-AD41-5A5B0FD810C5
:END:

Engaging some power tools to enhance the use of regular expressions in Emacs.

A nice native feature of Emacs is the =re-builder= package which allows you to build regular expressions with interactive feedback. It also allow you to work around some of the more annoying aspects of Emacs' native regular expression syntax. What it doesn't do is hook directly into some of the most common tasks you want regexp for such as =query-replace-regexp=.

The follow is code that is taken from Karthik Chikmagalur's fantastic blog entry on bridging that gap. Found here [[https://karthinks.com/software/bridging-islands-in-emacs-1/][Bridging Islands in Emacs]]

#+begin_src emacs-lisp

  (use-package re-builder
    :bind (("M-s %" . #'re-builder)
           :map reb-mode-map ("RET" . #'reb-replace-regexp)
           :map reb-lisp-mode-map ("RET" . #'reb-replace-regexp))
    :config
    (defvar my/re-builder-positions nil
      "Store point and region bounds before calling re-builder")

    (advice-add 're-builder
                :before
                (defun my/re-builder-save-state (&rest _)
                  "Save into `my/re-builder-positions' the point and region
  positions before calling `re-builder'."
                  (setq my/re-builder-positions
                        (cons (point)
                              (when (region-active-p)
                                (list (region-beginning)
                                      (region-end)))))
                  (message "Set positions to: %s" my/re-builder-positions)))

    (defun reb-replace-regexp (&optional delimited)
      "Run `query-replace-regexp' with the contents of re-builder. With
  non-nil optional argument DELIMITED, only replace matches
  surrounded by word boundaries."
      (interactive "P")
      (reb-update-regexp)
      (let* ((re (reb-target-value 'reb-regexp))
             (replacement (query-replace-read-to
                           re
                           (concat "Query replace"
                                   (if current-prefix-arg
                                       (if (eq current-prefix-arg '-) " backward" " word")
                                     "")
                                   " regexp"
                                   (if (with-selected-window reb-target-window
                                         (region-active-p)) " in region" ""))
                           t))
             (pnt (car my/re-builder-positions))
             (beg (cadr my/re-builder-positions))
             (end (caddr my/re-builder-positions)))
        (with-selected-window reb-target-window
          (goto-char pnt) ; replace with (goto-char (match-beginning 0)) if you want
                                          ; to control where in the buffer the replacement starts
                                          ; with re-builder
          (setq my/re-builder-positions nil)
          (reb-quit)
          (query-replace-regexp re replacement delimited beg end)))))

#+end_src

** Miscellaneous Enhancements

I generally find that when I want to use a `zap` command I'm using it to close space.

#+begin_src emacs-lisp

  (global-set-key (kbd "C-z") 'zap-up-to-char)
  (global-set-key (kbd "C-M-z") 'zap-to-char)

#+end_src

* Behavioral Enhancements

One of the few big holes in Emacs' basic functionality is its undo system. So I use a drop in replacement.

#+begin_src emacs-lisp

  ;; Clean and straightforward undo/redo
  (use-package undo-fu
    :config
    (setopt undo-fu-allow-undo-in-region t)
    :bind
    ("C-/" . undo-fu-only-undo)
    ("C-M-/" . undo-fu-only-redo))

  ;; Persist undo history across sessions
  (use-package undo-fu-session
    :config
    (setq undo-fu-session-incompatible-files '("/COMMIT_EDITMSG\\'" "/git-rebase-todo\\'"))
    (undo-fu-session-global-mode))

#+end_src

I don't want any bells on thanks

#+begin_src emacs-lisp

  (setq visible-bell nil
        ring-bell-function #'ignore)

#+end_src

Treat manual buffer switching, via =switch-to-buffer=, the same way as programmatic buffer switching. With this set =switch-to-buffer= will obey any display action rules in place. N.B. requires Emacs 27+.

#+begin_src emacs-lisp

  (setq switch-to-buffer-obey-display-actions t)

#+end_src

When I want a terminal I want a real terminal. =vterm= essentially add a 'real' terminal into Emacs via the libvterm library.

#+begin_src emacs-lisp

  (use-package vterm
    :init
    (setq vterm-max-scrollback 10000)
    :bind
    ("C-x !" . projectile-run-vterm))

#+end_src

Probably most this to a more sensible place when I come up with one; Swap out =M-x= for running =execute-extended-command=.

#+begin_src emacs-lisp

  (global-set-key (kbd "C-x C-m") 'execute-extended-command)

#+end_src

* Utility Functions

Miscellaneous utility functions. Perhaps to later be packaged up if I make =liminal= more of a Nano-like 'distro'.

Switch themes more cleanly than the default. Emacs themes are designed to be able to stack on top of each other. This behavior is not always what is wanted. This function disables any themes in place and them loads the requested them.

#+begin_src emacs-lisp

  (defun luda/switch-theme (theme)
    "Load THEME after unloading previously loaded themes.

  Unloading themes in this manned does not remove any
  customization done outside of themes."

    (interactive
     (list
      (intern (completing-read "Load custom theme: "
                               (mapcar 'symbol-name
                                       (custom-available-themes))))))
    (mapcar #'disable-theme custom-enabled-themes)
    (load-theme theme t))

#+end_src

Kill the current frame or exit emacs if the frame in question is the only one. Taken from [[https://github.com/rougier/nano-emacs/issues/128]]. Tweaked to confirm but only when killing the last frame. I've accidentally closed the last frame a few too many times for comfort.

#+begin_src emacs-lisp

  (defun luda/kill-frame ()
    "Delete frame or kill Emacs if there is only one frame."
    (interactive)
    (condition-case nil
        (delete-frame)
      (error
       (if (y-or-n-p (format "Are you sure you want to close the last frame?"))
           (save-buffers-kill-terminal)
         (message "Great, back to what you were doing then.")))))

  (global-set-key (kbd "C-x C-c") 'luda/kill-frame)

#+end_src

Generally speaking I don't like to have more two windows open at a time. When I do have two windows I don't always split them the way I want. Ergo the need to toggle between vertical and horizontal split.

#+begin_src emacs-lisp

  (use-package transpose-frame
    :bind
    ("C-x |" . transpose-frame))

#+end_src

When I want to kill a buffer I almost always want to kill the buffer I'm in. Occasionally I don't so remap =C-x k= to =kill-this-buffer= and shift =kill-buffer= to =C-x C-k=

#+begin_src emacs-lisp

  (keymap-set global-map "C-x k" 'kill-this-buffer)
  (keymap-set global-map "C-x C-k" 'kill-buffer)

#+end_src

One thing I miss a little from my Vim days was a quick keyboard shortcut for switching to the last buffer I visited, the 'alternate file' in Vim terms. In emacs this can be accomplished via call the =switch-to-buffer= function with a =nil= argument. This switches to whatever buffer is returned by =other-buffer=. I use this type of command when bouncing back and forth between two related files. This is also the use case I most commonly use for split windows. As such it makes sense to overload the =M-o= keymap to switch between splits if there are any and bounce between buffers if there aren't.

#+begin_src emacs-lisp

  (defun luda/hop-buffer ()
    (interactive)
    (if (= (length (window-list)) 1)
        (switch-to-buffer nil)
      (other-window 1)))

  (global-set-key (kbd "M-o") 'luda/hop-buffer)

#+end_src

* Specific Language Support

TreeSitter support covers a fair bit of territory for language support. There are however some gaps that need to be filled.

** Coffeescript

Unfortunately I still have to support some legacy =coffeescript= at my day job. Sensibly TreeSitter doesn't include a coffeescript parser. Ergo =coffee-mode=

#+begin_src emacs-lisp

  (use-package coffee-mode
    :config
    (setq coffee-tab-width 2))

#+end_src

** CSS

Regular CSS should be covered by the native TreeSitter functionality in tandem with =treesit-auto-mode=. However, I still had this in my config so I'll make it =INACTIVE= and resolve it as part of a cleanup pass.

I also need to figure out what to set up for SCSS as we lean on that heavily at my day job.

#+begin_src emacs-lisp

  (use-package css-mode
    :custom
    (css-indent-offset 2))

#+end_src

Maybe put this somewhere else but it works hand in hand with CSS so it's not the /wrong/ place to put it.

#+begin_src emacs-lisp

  (use-package rainbow-mode
    :custom
    (rainbow-html-colors nil)
    :hook (css-mode . rainbow-mode))

#+end_src

** EmacsLisp

Ah, the raison d'être

** ERB
:LOGBOOK:
- State "CALENDAR"   from              [2024-02-27 Tue 07:52]
:END:

At my day job we have a primarily Rails codebase. This means we have legacy ERB templates to deal with. These are not covered by TreeSitter but =web-mode= is the next best mode for dealing with many template languages. Currently I basically only use it for ERB templates but it serves as a powerful fallback option when things aren't covered by TreeSitter or a specific language mode that does the job better.

#+begin_src emacs-lisp

  (use-package web-mode
    :mode "\\.erb\\'")

#+end_src

** HAML + Slim

A Rails codebase also means HAML and Slim templates too. Sadly for my config's dependency graph =web-mode= is designed for template languages that are derived from HTML which HAML is not. So bring in its own mode package.

#+begin_src emacs-lisp

  (use-package haml-mode
    :defer t)

#+end_src

** Javascript/Typescript

=jtsx-mode= is a lightweight mode that piggybacks on Emacs' built in JSX/TSX mode and integrates with =TreeSitter= sprinkling some nice utilities over the native mode(s).

#+begin_src emacs-lisp

  (use-package jtsx
    :mode (("\\.jsx?\\'" . jsx-mode)
           ("\\.tsx?\\'" . tsx-mode))
    :config
    (setq js-indent-level 2)
    (setq typescript-ts-mode-indent-offset 2)
    (setq jtsx-switch-indent-offset 0)
    (setq jtsx-indent-statement-block-regarding-standalone-parent nil)
    (setq jtsx-jsx-element-move-allow-step-out t)
    (setq jtsx-enable-jsx-electric-closing-element t))

#+end_src

** Ruby

#+begin_src emacs-lisp

  (use-package ruby-ts-mode
    :mode "\\.rb\\'"
    :mode "\\.pryrc\\'"
    :mode "Rakefile\\'"
    :mode "Gemfile\\'")

#+end_src

** YAML

#+begin_src emacs-lisp

  (use-package yaml-ts-mode
    :mode "\\.y[a]?ml")

#+end_src

* Org Mode

One of the killer apps of Emacs the venerable OrgMode. Even more that the rest of the config the Org stuff is usually in flux. I love it but I've never totally gotten the hang of it can have yet to really settle on a workflow.

Various directory and file locations for use configuring Org.

#+begin_src emacs-lisp

  (setq luda/default-org-directory (expand-file-name "org" luda/local-root))
  (setq luda/sync-org-directory (expand-file-name "Dropbox/org" luda/local-root))
  (setq luda/beorg-directory (expand-file-name "Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org" luda/local-root))

  (setq luda/org-dir
        (if (file-directory-p luda/default-org-directory)
            luda/default-org-directory
          luda/sync-org-directory))

  (setq luda/journal-file (expand-file-name "journal.org" luda/org-dir))
  (setq luda/projects-file (expand-file-name "projects.org" luda/org-dir))
  (setq luda/org-id-locations-file (expand-file-name ".org-id-locations" luda/org-dir))

#+end_src

Define some custom todo keywords. I've been trying for ages to find a ToDo workflow/system that works. While my ADHD brain is great at finding such systems It's rubbish at using them. Currently I'm trying to simplify things and go with a 3+1 list system. Which goes something like this.

+ Calendar: Anything which has a specific date attached to it which isn't today.
+ Short: Anything that needs to be done *today*. N.B. things from the calendar with date of 'today' should move to short list.
+ Long: Everything that doesn't belong on once of the other lists.
+ Wait: A subset of the long list for items which depend on something from someone else.

#+begin_src emacs-lisp

  (setq luda/todo-keywords
        `((sequence
           "CALENDAR(c!)" "SHORT(s!)" "LONG(l!)" "WAIT(!w)" "|" "DONE(d!)" "NOPE(-!)")))

#+end_src

Configure Org itself

#+begin_src emacs-lisp

  (use-package org
    :init
    (setq org-export-backends
          '(ascii md html icalendar latex odt))
    :config
    (setq org-default-notes-file (expand-file-name "todo.org" luda/org-dir))
    (setq org-log-done 'time)
    (setq org-log-reschedule 'time)
    (setq org-log-into-drawer t)
    (setq org-startup-indented t)
    (setq org-startup-truncated nil)
    (setq org-todo-keywords luda/todo-keywords)
    (setq org-id-track-globally t)
    (setq org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
    (setq org-id-locations-file luda/org-id-locations-file)
    (setq org-id-locations-file-relative t)
    (setq org-fontify-whole-heading-line t)
    (setq org-agenda-files `(,luda/org-dir ,luda/beorg-directory))
    (setq org-latex-pdf-process
          '("tectonic %f"))

    (setq org-capture-templates
          `(("t" "Todo" entry (file+headline ,luda/projects-file "Tasks")
             "* TODO %?\n  %i\n  %a")
            ("pn" "Project Note" entry (file+headline ,luda/projects-file "Notes")
             "* Bench Note %?\n  %i\n  %a")
            ("j" "Journal" entry (file+olp+datetree ,luda/journal-file)
             "* %?\nEntered on %U\n  %i\n  %a")))

    ;; One of my big uses for Org is my literate config so having elisp as a template is a must
    (add-to-list 'org-structure-template-alist '("sl" . "src emacs-lisp"))

    :bind
    ("C-c a" . org-agenda)
    ("C-c c" . org-capture)
    ("C-c l" . org-store-link))

#+end_src

Personal overlay for org mode to 'beautify' it a bit. There are plenty of packages and approaches to this but rather than endlessly customizing a handful of different packages I figured I'd roll my own and take what I liked from different sources.

#+begin_src emacs-lisp

  

#+end_src

Deft brings the note taking approach of [[https://notational.net/][Notational Velocity]] into Emacs. Naturally it makes sense to hook it into Org. Still not sure if I'm totally sold on this approach over ordinary capturing. I do like it though.

#+begin_src emacs-lisp

  (require 'f)

  (defun deft-sidebar ()
    (interactive)
    (let ((sidebar-buf (generate-new-buffer deft-buffer)))
      (with-current-buffer sidebar-buf
        (deft-mode))
      (display-buffer-in-side-window sidebar-buf
                                     '((slot . 1)
                                       (dedicated . t)
                                       (window-height . 0.35)))))

  (use-package deft
    :commands deft
    :init
    (setq deft-directory (f-expand "notes/" luda/org-dir)
          deft-default-extension "org"
          deft-use-filename-as-title nil
          deft-use-filter-string-for-filename t
          deft-auto-save-interval -1.0
          deft-file-naming-rules
          '((noslash . "-")
            (nospace . "-")
            (case-fn . downcase)))
    :config
    (add-to-list 'deft-extensions "tex"))

  (use-package zetteldeft
    :init (zetteldeft-set-classic-keybindings))

#+end_src

* Version Control
** Magit

The gold standard of Git interfaces and one of the killer apps for Emacs. No real tweaks yet.

#+begin_src emacs-lisp

  (use-package magit
    :bind
    ("C-M-;" . magit-status))

  (defvar-keymap liminal-vc-branch-map
    :doc "Liminal prefix map for version control branch actions."
    "b" #'magit-checkout
    "c" #'magit-branch-create)

  (defvar-keymap liminal-vc-pull-map
    :doc "Liminal prefix map for version control pull/fetch actions."
    "p" #'magit-pull-from-pushremote
    "u" #'magit-pull-from-upstream
    "e" #'magit-pull-branch)

  (defvar-keymap liminal-vc-file-map
    :doc "Liminal prefix map for version control file actions."
    "r" #'magit-file-rename)

  (defvar-keymap liminal-vc-map
    :doc "Liminal prefix key maps version control operations ."
    "b" liminal-vc-branch-map
    "F" liminal-vc-pull-map
    "f" liminal-vc-file-map)

  (keymap-set global-map "C-x g" liminal-vc-map)

#+end_src

** Ediff

Taken from https://panadestein.github.io/emacsd/ a friendlier =ediff= experience. Basically does two things;

1. Save the current window config on entry and restores it on exit.
2. Sets the ediff config to a sensible, usable presentation with the files side by side and the control panel in the same frame, at the bottom.

#+begin_src emacs-lisp

  (defvar luda/ediff-original-windows nil)

  (defun luda/store-pre-ediff-winconfig ()
    "Stores the window arrangement before opening ediff."
    (setq luda/ediff-original-windows (current-window-configuration)))

  (defun luda/restore-pre-ediff-winconfig ()
    "Resets original window arrangement"
    (set-window-configuration luda/ediff-original-windows))

  (use-package ediff
    :hook ((ediff-before-setup . 'luda/store-pre-ediff-winconfig)
           (ediff-quit . 'luda/restore-pre-ediff-winconfig))
    :config
    (setq ediff-window-setup-function 'ediff-setup-windows-plain)
    (setq ediff-split-window-function 'split-window-horizontally))

#+end_src
