#+TITLE: Emacs Literate Configuration
#+AUTHOR: Luke D. Inglis
#+DATE: 11/2023
#+STARTUP: show2levels indent hidestars
#+PROPERTY: header-args :tangle (let ((org-use-tag-inheritance t)) (if (member "INACTIVE" (org-get-tags))  "no" "~/code/dotemacs/lit-init.el"))

* Emacs Literate Configuration
* Documentation
** Forwards

While learning Emacs I've tried a lot of different prepackaged 'distros'. Most notably, as an erstwhile (neo)vim user, Doom. After learning enough via that route and additionally deciding to try to give vanilla Emacs a solid try I'm leaving the prepackaged distros behind and building my own configuration.

It won't be 100% from scratch (are they ever?) as I really like the approach of the NΛNO configuration project and have built from that. Over all I aim for a practically minimalist approach.

Naturally my config is built 'on the shoulders of giants' where much more experienced Emacs users have gone before. With the goal of learning in mind I aim to do my best to not put anything in this config unless I understand how it works.

To wit, giants on whose shoulders I stand. In no particular order.

+ [[https://github.com/rememberYou/.emacs.d][Terencio Agozzino]] (=rememberYou=)
+ [[https://github.com/rougier/dotemacs][Nicolas Rougier (rougier) - Author of NANO]]
+ [[https://github.com/daviwil/dotfiles/blob/master/Emacs.org][David Wilson (daviwil) - System Crafter]]

Big thanks to those from whom I have learned. (And copy and pasted from...)

As this config sprouted originally from N. Rougier's I will quote directly part of the preamble to his.

#+begin_quote

This document is a literate configuration for GNU Emacs written in [[https://orgmode.org/][org]] format. It cannot be used directly and needs to be transformed to extract all the different code blocks into a single configuration file. This is done using the [[help:org-babel-tangle][org-babel-tangle]] function that "extract the bodies of all source code blocks from the current file into their own source-specific files". You can try by yourself by typing the sequence: =C-c C-v t= (org-babel-execute-subtree).

#+end_quote

*** To Do [2/4]                                                  :INACTIVE:

Simply put a list of concrete actions to take to enchance or solve issues with this configuration.

- [ ] Change underlying Coreutils on MacOS to be the GNU version and adjust config accordingly if necessary.
- [X] Extract the non-theme related settings from the =liminal-mode= settings
- [X] Switch to my own fork of the modeline
- [ ] Read up on =cycle-spacing=

*** Research [1/7]                                               :INACTIVE:

List of less tasks to do that are more theoretical or investigative than the concrete, actionable items above. N.B. the output of these tasks should include two things, one necessary and one conditional. The necessary item is a note with the result of investigating. The conditional item is a To Do added to the list above if the result of the research is an actionable item.

- [ ] [[https://github.com/mickeynp/combobulate][Combobulate]] - Structure navigation and editing. Leverages tree-sitter. An alternative to Objed.
- [ ] [[Https://github.com/radian-software/prescient.el][Prescient]] - An extra layer of intelligence for completion sorting and filtering
- [X] [[https://github.com/oantolin/embark][Embark]]. Looks super cool. Maybe able to combine with Objed or Combobulate.
  Note: I've already added Embark but have yet to use it for much. Spend some time getting to know it.
- [ ] [[https://github.com/kickingvegas/casual-dired][Casual Dired]] - A transient window based 'porcelain' for Dired aimed at simplifying the UX.
- [0/2] [[https://protesilaos.com/emacs/denote][Denote]] - Look into as an alternative to Deft + Zetteldeft for note taking.
  - [ ] How does it compare to (Zettel)Deft
  - [ ] Can it be massaged to work with [[https://logseq.com/][LogSeq]]
- [ ] [[https://www.orgroam.com/][Org Roam]] - Much heavier than Denote but might also fit with how I think about how I'd like to use Org mode. Additionally can be configured in such a way as to work well with [[https://logseq.com/][LogSeq]] which seems appealing
- [ ] As per the last two items look into various ways in which [[https://logseq.com/][LogSeq]] and Emacs/OrgMode can talk to each other and determine the best way of syncing the two.
- [ ] [[https://github.com/alphapapa/activities.el][Activities]] - Package built around the idea of saving files, buffers, and
  other related state defined as an /activity/.

*** Possible packages to add                                     :INACTIVE:

Listed separately from the above To Do list a holding place for packages that I've come across or seen/heard mention of that look worth investigating but maybe not enough that I need to 'To Do' them.

+ [[https://github.com/progfolio/doct][Doct]] - from its GitHub page is '...a function that provides an alternative, declarative syntax for describing Org capture templates.'
+ [[https://github.com/namilus/denote-menu][Denote Menu]] - If I end up using Denote this looks like a nice addon to it

* Core
** Header

This will generate a header at the top of the tangled file to indicate it is generated and is not meant to be modified directly.

#+begin_src emacs-lisp :epilogue (format-time-string ";; Last generated on %c")

  ;;; Sensible Emacs --- A literate configuration -*- lexical-binding: t -*-
  ;;; This file has been generated from dotemacs.org file. DO NOT EDIT.

  ;;; Copyright (C) 2024 Luke D. Inglis

  ;;; This file is free software; you can redistribute it and/or modify
  ;;; it under the terms of the GNU General Public License as published by
  ;;; the Free Software Foundation; either version 3, or (at your option)
  ;;; any later version.

  ;;; This file is distributed in the hope that it will be useful,
  ;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
  ;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ;;; GNU General Public License for more details.

  ;;; For a full copy of the GNU General Public License
  ;;; see <https://www.gnu.org/licenses/>.

#+end_src

** Early Init                                                   :HOOK:OTHER:
:PROPERTIES:
:header-args:emacs-lisp: :tangle ~/code/dotemacs/early-init.el
:END:

This code is meant to go to the [[file:early-init.el][early-init.el]] file.

#+begin_src emacs-lisp

  (setq
   site-run-file nil                         ; No site-wide run-time initializations.
   inhibit-default-init t                    ; No site-wide default library
   gc-cons-threshold most-positive-fixnum    ; Very large threshold for garbage
                                          ; collector during init
   package-enable-at-startup nil)            ; We'll use straight.el

  (setq native-comp-eln-load-path
        (list (expand-file-name "eln-cache" user-emacs-directory)))

  ;; Reset garbage collector limit after init process has ended (8Mo)
  (add-hook 'after-init-hook
            #'(lambda () (setq gc-cons-threshold (* 8 1024 1024))))

#+end_src

** Packages management                                            :PERSONAL:

Using [[https://github.com/raxod502/straight.el][straight.el]] for package management and disable checking (for speedup). Hook it up to =use-package= by default at least for the time being.

#+begin_src emacs-lisp

  (unless (featurep 'straight)
    ;; Bootstrap straight.el
    (defvar bootstrap-version)
    (let ((bootstrap-file
           (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
          (bootstrap-version 5))
      (unless (file-exists-p bootstrap-file)
        (with-current-buffer
            (url-retrieve-synchronously
             "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
             'silent 'inhibit-cookies)
          (goto-char (point-max))
          (eval-print-last-sexp)))
      (load bootstrap-file nil 'nomessage)))

  (setq straight-check-for-modifications nil)

#+end_src

Library load paths with a special case for mu4e (you may need to adapt this path).

#+begin_src emacs-lisp

  (add-to-list 'load-path
               (expand-file-name "lisp" user-emacs-directory))

#+end_src

** Packages installation

Packages used in this specific configuration. You may want to adapt this list. The first time this sequence will be executed, *it will take a long time*. Then, at next restart, it should be very fast (less than 1 second because it won't install anything basically).

#+begin_src emacs-lisp

  (setq package-list
        '(
          accent               ; Easier access to accented characters
          ace-window           ; Easier moving between windows
          apheleia             ; Code formatting without the pain and blocking
          avy                  ; Jump to things (but really much, much more...)
          cape                 ; Completion At Point Extensions
          circadian            ; Change my theme in rhythm with nature
          command-log-mode     ; More insight into what commands are being run/looks fancy when showing off
          consult              ; Consulting completing-read
          consult-lsp          ; LSP extras for consult to, well, consult
          corfu                ; Completion Overlay Region FUnction
  				denote
  				doct                 ; (D)eclarative (O)rg (C)apture (T)emplates
  				eglot-booster        ; Enable eglot to use the emacs-lsp-booster Rust program
          embark
          embark-consult
          exec-path-from-shell ; Get environment variables such as $PATH from the shell
          flycheck             ; Enhanced syntax checking, more flexible than flymake
          flycheck-eglot       ; Allow Flycheck to understand Eglot as a checker
          haml-mode            ; Rails templates not covered by treesitter or web-mode
          helpful              ; A better help buffer
          magit                ; A Git porcelain inside Emacs.
          marginalia           ; Enrich existing commands with completion annotations
          markdown-mode        ; Major mode for Markdown-formatted text
          no-littering         ; Keep our things clean and tidy
          orderless            ; Completion style for matching regexps in any order
  				pdf-tools
          projectile           ; Project scoped stuffness
          rg                   ; Ripgrep for speed and profit(?)
          save-visited-files   ; Simplest form of session persistance
          surround
          tempel
          tempel-collection
          treesit-auto
          undo-fu              ; Work around Emacs' clunky undo interface
          undo-fu-session      ; Persistant undo across sessions
          vertico              ; VERTical Interactive COmpletion
          vertico-posframe
          visual-fill-column   ; Nicer wrapping mostly for text modes
          vterm                ; A real terminal emulator running in Emacs
          web-mode             ; Uber mode for web templating languages
          which-key            ; Discovery method for key bindings
          ))

  ;; Install packages that are not yet installed
  (dolist (package package-list)
    (straight-use-package package))

  (straight-use-package
   '(jtsx :type git :host github :repo "llemaitre19/jtsx"))

  (straight-use-package
   '(asdf :type git :host github :repo "tabfugnic/asdf.el"))

  (straight-use-package
   '(eglot-ltex :type git :host github :repo "emacs-languagetool/eglot-ltex"))

  (straight-use-package
   '(use-package-xdg :type git :host codeberg :repo "rossabaker/use-package-xdg"))

  (straight-use-package '(org :type built-in))

#+end_src

** Meta-Configuration

Setup and tooling specifically related to this configuration itself.

*** Init time

Display a message to the *Messages* buffer showing the Emacs init time.

#+begin_src emacs-lisp

  (let ((inhibit-message t))
    (message "Welcome to GNU Emacs / Sensible edition")
    (message (format "Initialization time: %s" (emacs-init-time))))

#+end_src

*** Configuration reload

#+begin_src emacs-lisp

  (defun reload-init-file ()
    "Reload the file referenced by `user-init-file`."

    (interactive)
  	(load-file (expand-file-name "init.el" user-emacs-directory)))

  (keymap-global-set "<f5>" 'reload-init-file)

#+end_src

** Backups Etc.

Use [[https://github.com/emacscollective/no-littering][no-littering]] to keep my config directory tidier. Configured using the settings advised by [[https://rossabaker.com/configs/emacs/][Ross A. Baker]].

#+begin_src emacs-lisp

  (use-package no-littering
    :init
    (setq no-littering-etc-directory "~/.cache/emacs/etc/"
          no-littering-var-directory "~/.cache/emacs/var/")
    (when (fboundp 'startup-redirect-eln-cache)
      (startup-redirect-eln-cache
       (convert-standard-filename
        (expand-file-name  "eln-cache/" no-littering-var-directory))))
    (setq vc-make-backup-files nil     ; No backup of files under version contr
          backup-by-copying t          ; Don't clobber symlinks
          version-control t            ; Version numbers for backup files
          delete-old-versions t        ; Delete excess backup files silently
          kept-old-versions 3          ; Number of old versions to keep
          kept-new-versions 6          ; Number of new versions to keep
          delete-by-moving-to-trash t  ; Delete files to trash
          create-lockfiles nil)        ; More trouble than worth
    (setq backup-directory-alist
          `((".*" . ,(no-littering-expand-var-file-name "backup/")))
          auto-save-file-name-transforms
          `((".*" ,(no-littering-expand-var-file-name "auto-save/") t))))

#+end_src

#+begin_src emacs-lisp

  (setq bookmark-default-file (expand-file-name "bookmark" user-emacs-directory))

#+end_src

Enable and tweak =recentf-mode= to keep track of files recently operated on.

#+begin_src emacs-lisp

  (use-package recentf
    :custom
    (recentf-max-menu-items 10)
    (recentf-max-saved-items 100)
    :init
    (recentf-mode t))

#+end_src

Preservre cursor position per file across sessions.

#+begin_src emacs-lisp

  (use-package saveplace
    :custom
    (save-place-file (expand-file-name "saveplace" user-emacs-directory))
    (save-place-forget-unreadable-files t))

#+end_src

** History :HOOK:

Remove text properties for kill ring entries (see https://emacs.stackexchange.com/questions/4187). This saves a lot of time when loading it.

#+begin_src emacs-lisp

  (defun unpropertize-kill-ring ()
    (setq kill-ring (mapcar 'substring-no-properties kill-ring)))

  (add-hook 'kill-emacs-hook 'unpropertize-kill-ring)

#+end_src

We save every possible history we can think of.

#+begin_src emacs-lisp

  (use-package savehist
    :init
    (savehist-mode t)
    :custom
    (kill-ring-max 50)
    (history-length 50)
    (savehist-additional-variables
     '(kill-ring
       command-history
       set-variable-value-history
       custom-variable-history
       query-replace-history
       read-expression-history
       minibuffer-history
       read-char-history
       face-name-history
       bookmark-history
       file-name-history))
    :config
    (put 'minibuffer-history         'history-length 50)
    (put 'file-name-history          'history-length 50)
    (put 'set-variable-value-history 'history-length 25)
    (put 'custom-variable-history    'history-length 25)
    (put 'query-replace-history      'history-length 25)
    (put 'read-expression-history    'history-length 25)
    (put 'read-char-history          'history-length 25)
    (put 'face-name-history          'history-length 25)
    (put 'bookmark-history           'history-length 25))

#+end_src

No duplicates in history

#+begin_src emacs-lisp

  (setq history-delete-duplicates t)

#+end_src

Start history mode.

#+begin_src emacs-lisp

  (let (message-log-max)
    (savehist-mode))

#+end_src

** Path

Pull my full set of environmental variables into Emacs. This is most important on MacOS where I am currently spending all of my time.

#+begin_src emacs-lisp

  (use-package exec-path-from-shell
    :init
    (exec-path-from-shell-initialize))

#+end_src

Make Emacs aware of the proper paths for the [[https://asdf-vm.com/][asdf version manager]].

#+begin_src emacs-lisp

  (use-package asdf
    :config
    (asdf-enable))

#+end_src

point to my local root directory. Mostly for the sake of Org later on in the config.

#+begin_src emacs-lisp

  (setq luda/local-root "~/")

#+end_src

** MacOS specific settings

Juggle a few modifier keys to make things a little more comfortable. Tell dired not to use the underlying =ls= command on Mac since it doesn't use GNUVC oreutils which is what dired expects.

#+begin_src emacs-lisp

  (when (string-equal system-type "darwin")
    (setq mac-option-modifier 'super)
    (setq mac-command-modifier 'meta)
    (setq dired-use-ls-dired nil))

#+end_src

* Frame

A variation on =make-frame= that opens to the =*scratch*= buffer rather than the current buffer.

#+begin_src emacs-lisp

  (defun luda/make-scratch-frame ()
    "Create a new frame and switch to *scratch* buffer."

    (interactive)
    (select-frame (make-frame))
    (switch-to-buffer "*scratch*"))

  (defvar-keymap liminal-frame-map
    :doc "Liminal prefix map for frame operations."
    "m" #'make-frame
    "n" #'luda/make-scratch-frame)

  (keymap-set global-map "M-n" liminal-frame-map)

#+end_src

* Visual
** Sensible Settings

As part of it's setup it is running the =sensible-mode= function which sets a number of sensible defaults and settings. For me it would make more sense for these to be there own separate setup but I haven't extracted them yet.

#+begin_src emacs-lisp

  (use-package sensible-settings
    :load-path "~/code/sensible-settings"
    :init
    (setopt sensible-font-size 16
            sensible-manage-cursor t
            sensible-manage-fonts t
            sensible-manage-ui t
            sensible-manage-ux t)
    :config
    (sensible-mode))

#+end_src

** Sensible Themes

New theme ideas I'm playing around with using [[https://www.reasonable.work/colors/][Reasonable Colors]].

#+begin_src emacs-lisp

  (use-package sensible-themes
  	:after 'sensible-settings
    :load-path "~/code/sensible-themes")

#+end_src

** Liminal modeline

I like the idea and the behavior of this modeline but there are a few more things that I would have present that are missing from it. I have forked it but haven't made any useful changes made.

#+begin_src emacs-lisp

  (use-package sensible-modeline
    :after 'sensible-themes
    :load-path "~/code/sensible-modeline"
    :init
    (setopt mode-line-format nil)
    :hook
    (prog-mode            . sensible-modeline-prog-mode)
    (text-mode            . sensible-modeline-text-mode)
    (org-mode             . sensible-modeline-org-mode)
    (term-mode            . sensible-modeline-term-mode)
    (vterm-mode           . sensible-modeline-term-mode)
    (messages-buffer-mode . sensible-modeline-message-mode)
    (org-capture-mode     . sensible-modeline-org-capture-mode)
    (org-agenda-mode      . sensible-modeline-org-agenda-mode))

#+end_src

** Circadian

I prefer the legibility of a well designed light theme when the lighting is good. However, I don't want to burn my retinas at night. Thankfully =circadian= exists to automatically adjust my theme at sunrise/sunset in my local area.

#+begin_src emacs-lisp

  (use-package circadian
    :custom
    (calendar-latitude 42.4)
    (calendar-longitude -71.0)
    (circadian-themes '((:sunrise . sensible-amber-light)
                        (:sunset  . sensible-azure-dark)))
    :config
    (circadian-setup))

#+end_src

** Miscellaneous visual settings.

Nicer display of text lines visually.

#+begin_src emacs-lisp

  (setq-default line-spacing 1)
  (global-visual-line-mode)

#+end_src

Always waffle on how minimal to be. Right now line numbers in prog modes are useful enough to allow within my minimal aesthetic. Or maybe not. For now.

#+begin_src emacs-lisp

  (use-package display-line-numbers
    :custom
    (display-line-numbers-widen t)
    :hook
    ((prog-mode conf-mode) . display-line-numbers-mode))

#+end_src

* PDF

#+begin_src emacs-lisp

  (use-package pdf-tools
    :config
    (pdf-tools-install)
    (setq-default pdf-view-display-size 'fit-width)
    (define-key pdf-view-mode-map (kbd "C-s") 'isearch-forward)
    :custom
    (pdf-annot-activate-created-annotations t "automatically annotate highlights"))

  (add-hook 'pdf-view-mode-hook (lambda() (display-line-numbers-mode -1)))

#+end_src

* Vertico

Building on Emacs own =completing-read= function Vertico provides a minimalist UI for completion in the minibuffer. It can be thought of as a sleeker, more minimalist alternative to [[https://github.com/abo-abo/swiper][Ivy]] or [[https://github.com/emacs-helm/helm][Helm]].

#+begin_src emacs-lisp

  (use-package vertico
    :bind (:map vertico-map
                ("C-<backspace>" . vertico-directory-up))
    :custom
    (vertico-resize t)
    (vertico-multiform-categories ; Choose a multiform
     '((file reverse)
       (consult-location)
       (imenu buffer)
       (library reverse indexed)
       (t reverse)
       ))
    (vertico-multiform-commands
     '(("flyspell-correct-*" grid reverse)
       (org-refile grid reverse indexed)
       (consult-yank-pop indexed)
       (consult-flycheck)
       (consult-lsp-diagnostics)
       ))
    :init
    (vertico-mode))

#+end_src

* Consult

What Vertico is to Ivy [[https://github.com/minad/consult][Consult]] is to Ivy's =counsel-mode=. It provides searchable replacements to many common Emacs commands.

#+begin_src emacs-lisp

  (defun wrapper/consult-ripgrep (&optional dir given-initial)
    "Pass the region to consult-ripgrep if available.

  DIR and GIVEN-INITIAL match the method signature of `consult-wrapper'."
    (interactive "P")
    (let ((initial
           (or given-initial
               (when (use-region-p)
                 (buffer-substring-no-properties (region-beginning) (region-end))))))
      (consult-ripgrep dir initial)))

  (use-package consult
    :config
    (recentf-mode)
    :bind (
           ("M-s d" . consult-fd) ;; Requires having fd installed otherwise use consult-find
           ("M-s c" . consult-locate)
           ("M-s g" . consult-grep)
           ("M-s G" . consult-git-grep)
           ("M-s r" . wrapper/consult-ripgrep)
           ("M-s l" . consult-line)
           ("M-s L" . consult-line-multi)
           ("M-s k" . consult-keep-lines)
           ("M-s u" . consult-focus-lines)
           ("M-s <SPC>"   . consult-buffer)
           ("M-y"   . consult-yank-pop)
           ("C-x M-k"   . consult-kmacro)
           ("M-g g" . consult-goto-line)
           ("M-g i" . consult-imenu)
           ("M-g o" . consult-outline)
           ("C-x b" . consult-bookmark)))

#+end_src

* Orderless

Orderless enhances completion functions allowing for searching by space delimited terms. The order of these terms does not matter, hence the name.

#+begin_src emacs-lisp

  (use-package orderless
    :config
    (setq completion-styles '(orderless partial-completion basic))
    (setq completion-category-defaults nil)
    (setq completion-category-overrides '((file (styles partial-completion)))))

#+end_src

* Corfu

Another package from =minad= (author of Vertico and Consult) Corfu is the 'in-buffer completion counterpart' to Vertico. Similarly it provides a minimalist wrapper around native bahaviors to provide an enhanced experience. Corfu hooks into Emacs' native =complete-in-region= and leverages whatever sources are available from =completion-at-point-functions= as sources for completion options.

#+begin_src emacs-lisp

  (defun corfu-x-eshell-hook ()
    "Set up Corfu behaviors in a shell friendly way."
    (setq-local corfu-auto nil)
    (corfu-mode))

  (use-package corfu
    :init
    (setq corfu-cycle t
          corfu-auto t
          corfu-on-exact-match nil)
    (corfu-history-mode)
    (corfu-echo-mode)
    (global-corfu-mode)
    :hook
    (eshell-mode . corfu-x-eshell-hook))

#+end_src

* Cape

Yet another package from =minad=. As mentioned Corfu leverages the =completion-at-point-functions= to populate its options. Cape complements it by providing a suite of such functions, usually referred to as Capfs.

#+begin_src emacs-lisp

  (defun luda/eglot-capf ()
    (setq-local completion-at-point-functions
                (list ((cape-capf-buster #'eglot-completion-at-point)
  										 #'cape-file))))

  (defun luda/cape-capf-setup-lsp ()
    "Replace the default `lsp-completion-at-point' with its
  `cape-capf-buster' version."
    (setf (elt (cl-member 'lsp-completion-at-point completion-at-point-functions) 0)
          (cape-capf-buster #'eglot-completion-at-point))
    (add-to-list 'completion-at-point-functions #'cape-dabbrev t))

  (defun luda/cape-capf-setup-org ()
    (add-to-list 'completion-at-point-functions (cape-capf-super #'cape-dict #'cape-dabbrev)))

  (defun luda/cape-capf-setup-git-commit ()
    (let ((result))
      (dolist (element '(cape-dabbrev cape-symbol) result)
        (add-to-list 'completion-at-point-functions element))))

  (use-package cape
    :config
    (setq completion-category-overrides '((eglot (styles orderless))
                                          (eglot-capf (styles orderless))))
    :hook
    ((eglot-managed-mode . luda/eglot-capf)
     (org-mode . luda/cape-capf-setup-org)
     (git-commit-mode . luda/cape-capf-setup-git-commit)))

                       #+end_src
* Marginalia

Marginalia adds rich annotations to the minibuffer completions. Good for quick reference and discoverability.

#+begin_src emacs-lisp

  (use-package marginalia
    :init
    (marginalia-mode)
    :bind (:map minibuffer-local-map
                ("M-A" . marginalia-cycle)))

#+end_src

* Embark

#+begin_src emacs-lisp

  (use-package embark
    :bind
    (("C-." . embark-act)         ;; pick some comfortable binding
     ("M-." . embark-dwim)        ;; good alternative: M-.
     ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'

    :init

    ;; Optionally replace the key help with a completing-read interface
    (setq prefix-help-command #'embark-prefix-help-command)

    ;; Show the Embark target at point via Eldoc. You may adjust the
    ;; Eldoc strategy, if you want to see the documentation from
    ;; multiple providers. Beware that using this can be a little
    ;; jarring since the message shown in the minibuffer can be more
    ;; than one line, causing the modeline to move up and down:

    ;; (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
    ;; (setq eldoc-documentation-strategy #'eldoc-documentation-compose-eagerly)

    :config

    ;; Hide the mode line of the Embark live/completions buffers
    (add-to-list 'display-buffer-alist
                 '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                   nil
                   (window-parameters (mode-line-format . none)))))

  ;; Consult users will also want the embark-consult package.
  (use-package embark-consult
    :hook
    (embark-collect-mode . consult-preview-at-point-mode))

#+end_src

* Tempel

Another minad package to try. This time template expansion.

#+begin_src emacs-lisp

  (use-package tempel
    ;; Require trigger prefix before template name when completing.
    :custom
    (tempel-trigger-prefix "<")

    :bind (("M-=" . tempel-complete) ;; Alternative tempel-expand
           ("M-*" . tempel-insert))
    :init

    ;; Setup completion at point
    (defun tempel-setup-capf ()
      ;; Add the Tempel Capf to `completion-at-point-functions'.
      ;; `tempel-expand' only triggers on exact matches. Alternatively use
      ;; `tempel-complete' if you want to see all matches, but then you
      ;; should also configure `tempel-trigger-prefix', such that Tempel
      ;; does not trigger too often when you don't expect it. NOTE: We add
      ;; `tempel-expand' *before* the main programming mode Capf, such
      ;; that it will be tried first.
      (setq-local completion-at-point-functions
                  (cons #'tempel-expand
                        completion-at-point-functions)))

    (add-hook 'conf-mode-hook 'tempel-setup-capf)
    (add-hook 'prog-mode-hook 'tempel-setup-capf)
    (add-hook 'text-mode-hook 'tempel-setup-capf))

  ;; Optional: Add tempel-collection.
  ;; The package is young and doesn't have comprehensive coverage.
  (use-package tempel-collection)

#+end_src

* Ace Window

#+begin_src emacs-lisp

  (use-package ace-window
    :bind
    ("M-o" . 'ace-window)
    :config
    (setq aw-keys '(?a ?s ?d ?f ?j ?k ?l)
          aw-dispatch-always t
          aw-dispatch-alist
          '((?x aw-delete-window "Ace - Delete Window")
            (?c aw-swap-window "Ace - Swap Window")
            (?n aw-flip-window)
            (?v aw-split-window-vert "Ace - Split Vert Window")
            (?h aw-split-window-horz "Ace - Split Horz Window")
            (?m delete-other-windows "Ace - Maximize Window")
            (?g delete-other-windows)
            (?b balance-windows)
            (?u (lambda ()
                  (progn
                    (winner-undo)
                    (setq this-command 'winner-undo))))
            (?r winner-redo))))

#+end_src

Not directly related to ace but philosophically related. Key binding for quickly hopping between the current buffer and the last visited one.

#+begin_src emacs-lisp

  (keymap-global-set "C-M-o" 'mode-line-other-buffer)

#+end_src

* Save Visited Files

I've looked around for different types of session management for Emacs. For the
most part I don't want anything more than just remembering the files I had open
if I need to quit out for some reason. Thankfully someone else had the same
idea.

#+begin_src emacs-lisp

  (use-package save-visited-files
    :init
    (save-visited-files-mode t)
    :custom
    (save-visited-files-location (expand-file-name "save-visited-files" user-emacs-directory))
    (save-visited-files-ignore-tramp-files t)
    (save-visited-files-ignore-directories nil)
    (save-visited-files-auto-restore nil))

#+end_src

* Minibuffer

#+begin_src emacs-lisp

  ;; Add prompt indicator to `completing-read-multiple'.
  ;; We display [CRM<separator>], e.g., [CRM,] if the separator is a comma.
  (defun crm-indicator (args)
    (unless 
  			(cons (format "[crm: %s] %s"
  										(replace-regexp-in-string
  										 "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
  										 crm-separator)
  										(car args))
  						(cdr args)))
  	(advice-add #'completing-read-multiple :filter-args #'crm-indicator)

  	;; Do not allow the cursor in the minibuffer prompt
  	(setq minibuffer-prompt-properties
  				'(read-only t cursor-intangible t face minibuffer-prompt))
  	(add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)

  	;; Enable recursive minibuffers
  	(setq enable-recursive-minibuffers t)

#+end_src

* Modes Meta

Stuff related, at least philosophically to the management of modes themselves.

#+begin_src emacs-lisp

  (defvar-keymap liminal-modes-toggle-map
    :doc "Liminal prefix key maps | mode toggling."
    "w" #'whitespace-mode)

  (keymap-set global-map "C-x m" liminal-modes-toggle-map)

#+end_src

* Which key for discoverability

Add which-key for discoverability and because I can only ever remember my most used key bindings.

#+begin_src emacs-lisp

  (use-package which-key
    :config
    (setq which-key-idle-delay 0.75)
    (which-key-mode))

#+end_src

* Projectile

I had stopped exploring projectile for a bit but never removed it. I'm taking a second look now.

#+begin_src emacs-lisp

  (use-package projectile
  	:config
  	(projectile-mode)
  	:custom
  	(projectile-project-search-path `(,(concat luda/local-root "code")))
  	:bind (:map projectile-mode-map
  							("s-," . projectile-command-map)))

#+end_src

* LSP

Use Eglot for LSP integration. Fewer options than =lsp-mode= but it's built-in and covers the ground that I need it for right noe

#+begin_src emacs-lisp

  (use-package eglot
    :bind (:map eglot-mode-map
                ("C-x l r" . eglot-rename)
                ("M-k" . eglot-code-actions))
    :hook ((prog-mode . eglot-ensure)
           (css-mode . eglot-ensure))
    :config
    (setq eldoc-echo-area-use-multiline-p nil)
    (add-to-list 'eglot-server-programs
                 '(ruby-ts-mode . ("solargraph" "stdio"))))

  (use-package eglot-booster
    :after eglot
    :config
    (eglot-booster-mode))

#+end_src

#+begin_src emacs-lisp

  (use-package eglot-ltex
  	:hook
  	(text-mode . (lambda ()
  								 (require 'eglot-ltex)
  								 (eglot-ensure)))
  	:init
  	(setq eglot-ltex-server-path "/usr/local/bin/ltex-ls"))

#+end_src
* Code analysis:
** Flycheck

Flycheck to run checkers, linters, etc. Also hook Flycheck and Eglot together so that errors, warnings. etc. returned from language servers are piped through Flycheck.

#+begin_src emacs-lisp

  (use-package flycheck
    :config
    (global-flycheck-mode))

  (use-package flycheck-eglot
    :hook
    (eglot-managed-mode . flycheck-eglot-mode)
    :after (flycheck eglot))

#+end_src

** Jinx

Fast just-in-time spell checker leveraging the power of the enchant library.

#+begin_src emacs-lisp

  (use-package jinx
  	:hook (emacs-startup . global-jinx-mode)
  	:bind (("M-$" . jinx-correct)
  				 ("C-M-$" . jinx-languages)))

#+end_src
* Treesitter

I tried the =treesit-auto= package for automagically handling installation and activation of Treesitter parsers/modes but it wasn't working as smoothly as I'd hoped so I'm going to just handle things manually for the time being.

Edit: trying =treesit-auto= yet again as I was unable to get /anything/ to work smoothly/right.

#+begin_src emacs-lisp

  (setq treesit-language-source-alist
        '((css "https://github.com/tree-sitter/tree-sitter-css")
          (lua "https://github.com/MunifTanjim/tree-sitter-lua")
          (ruby "https://github.com/tree-sitter/tree-sitter-ruby")
          (dockerfile "https://github.com/camdencheek/tree-sitter-dockerfile")
          (scss "https://github.com/serenadeai/tree-sitter-scss")
          (elisp "https://github.com/Wilfred/tree-sitter-elisp")
          (go "https://github.com/tree-sitter/tree-sitter-go")
          (html "https://github.com/tree-sitter/tree-sitter-html")
          (json "https://github.com/tree-sitter/tree-sitter-json")
          (make "https://github.com/alemuller/tree-sitter-make")
          (markdown "https://github.com/ikatyang/tree-sitter-markdown")
          (toml "https://github.com/tree-sitter/tree-sitter-toml")
          (yaml "https://github.com/ikatyang/tree-sitter-yaml")))

  (dolist (ts-pair treesit-language-source-alist)
    (let ((language (car ts-pair)) (repo (cadr ts-pair)))
      (unless (treesit-language-available-p language)
        (message "Installing parser for %s from %s" language repo)
        (treesit-install-language-grammar language))))

  (use-package treesit-auto
    :custom
    (treesit-auto-install 'prompt)
    :config
    (global-treesit-auto-mode))

#+end_src

* Formatting

I played around with using Eglot and the LSP for formatting and I might still
do that but it was going to take some configuration to get it to not do
annoying things with the formatting like always using actual tabs and
defaulting to width 8 tabs. Both of those being 'issues' with how the LSP spec
defines tabSize and what Emacs considers a tab and what it considers
indentation.

So for the time being I am using [[https://github.com/radian-software/apheleia][Apheleia]]. Currentinly only set up for Javascript.

#+begin_src emacs-lisp

  (use-package apheleia
    :custom
    ((alist-get 'prettier apheleia-formatters)
     '(npx "prettier" "--print-width" "100" file))
    :config
    (add-to-list 'apheleia-mode-alist '(jsx-mode . prettier))
    (add-to-list 'apheleia-mode-alist '(ruby-ts-mode . rubocop)))

#+end_src

* Text editing and navigation

For a very long time I was a Vim/Neovim user. I love Vim but I've really gotten absorbed into the world of Emacs. Neovim in particular feels like a great tool to use but Emacs feels more like an extension of my brain. I'm pretty all in at this point.

However, there are a few things that I really miss about the Vim and the plugins I used in my setup. Some are bigger than others.

** Avy

Just looking at the tin [[https://github.com/abo-abo/avy][Avy]] is a /...package for jumping to visible text using a char-based decision tree./ However, as Karthik Chikmagalur puts it /Avy can do any thing/.

I'm taking his lead and trying it out as the power tools he makes it out to be.

#+begin_src emacs-lisp

  (defun avy-action-embark (pt)
    (unwind-protect
        (save-excursion
          (goto-char pt)
          (embark-act))
      (select-window
       (cdr (ring-ref avy-ring 0))))
    t)

  (defun avy-action-copy-whole-line (pt)
    (save-excursion
      (goto-char pt)
      (cl-destructuring-bind (start . end)
          (bounds-of-thing-at-point 'line)
        (copy-region-as-kill start end)))
    (select-window
     (cdr
      (ring-ref avy-ring 0)))
    t)

  (defun avy-action-yank-whole-line (pt)
    (avy-action-copy-whole-line pt)
    (save-excursion (yank))
    t)

  (defun avy-action-kill-whole-line (pt)
    (save-excursion
      (goto-char pt)
      (kill-whole-line))
    (select-window
     (cdr
      (ring-ref avy-ring 0)))
    t)

  (defun avy-action-teleport-whole-line (pt)
    (avy-action-kill-whole-line pt)
    (save-excursion (yank)) t)

  (use-package avy
    :config
    (setf (alist-get ?. avy-dispatch-alist) 'avy-action-embark
          (alist-get ?k avy-dispatch-alist) 'avy-action-kill-stay
          (alist-get ?K avy-dispatch-alist) 'avy-action-kill-whole-line
          (alist-get ?t avy-dispatch-alist) 'avy-action-teleport
          (alist-get ?T avy-dispatch-alist) 'avy-action-teleport-whole-line
          (alist-get ?y avy-dispatch-alist) 'avy-action-yank
          (alist-get ?w avy-dispatch-alist) 'avy-action-copy
          (alist-get ?W avy-dispatch-alist) 'avy-action-copy-whole-line
          (alist-get ?Y avy-dispatch-alist) 'avy-action-yank-whole-line)
    :bind ("M-j" . avy-goto-char-timer))

#+end_src

** Occur

Yet another builtin I'm slowly learning to make the most of.

#+begin_src emacs-lisp

  (use-package occur
    :bind (:map isearch-mode-map ("C-o" . isearch-occur)))

#+end_src

** Regexen + Search and replace
:PROPERTIES:
:ID:       1739F061-BA7D-4A55-AD41-5A5B0FD810C5
:END:

Engaging some power tools to enhance the use of regular expressions in Emacs.

A nice native feature of Emacs is the =re-builder= package which allows you to build regular expressions with interactive feedback. It also allow you to work around some of the more annoying aspects of Emacs' native regular expression syntax. What it doesn't do is hook directly into some of the most common tasks you want regexp for such as =query-replace-regexp=.

The follow is code that is taken from Karthik Chikmagalur's fantastic blog entry on bridging that gap. Found here [[https://karthinks.com/software/bridging-islands-in-emacs-1/][Bridging Islands in Emacs]]

#+begin_src emacs-lisp

  (use-package re-builder
    :bind (("M-s %" . #'re-builder)
           :map reb-mode-map ("RET" . #'reb-replace-regexp)
           :map reb-lisp-mode-map ("RET" . #'reb-replace-regexp))
    :custom
    (reb-re-syntax 'string)
    :config
    (defvar my/re-builder-positions nil
      "Store point and region bounds before calling re-builder")

    (advice-add 're-builder
                :before
                (defun my/re-builder-save-state (&rest _)
                  "Save into `my/re-builder-positions' the point and region
  positions before calling `re-builder'."
                  (setq my/re-builder-positions
                        (cons (point)
                              (when (region-active-p)
                                (list (region-beginning)
                                      (region-end)))))
                  (message "Set positions to: %s" my/re-builder-positions)))

    (defun reb-replace-regexp (&optional delimited)
      "Run `query-replace-regexp' with the contents of re-builder. With
  non-nil optional argument DELIMITED, only replace matches
  surrounded by word boundaries."
      (interactive "P")
      (reb-update-regexp)
      (let* ((re (reb-target-value 'reb-regexp))
             (replacement (query-replace-read-to
                           re
                           (concat "Query replace"
                                   (if current-prefix-arg
                                       (if (eq current-prefix-arg '-) " backward" " word")
                                     "")
                                   " regexp"
                                   (if (with-selected-window reb-target-window
                                         (region-active-p)) " in region" ""))
                           t))
             (pnt (car my/re-builder-positions))
             (beg (cadr my/re-builder-positions))
             (end (caddr my/re-builder-positions)))
        (with-selected-window reb-target-window
          (goto-char pnt) ; replace with (goto-char (match-beginning 0)) if you want
                                          ; to control where in the buffer the replacement starts
                                          ; with re-builder
          (setq my/re-builder-positions nil)
          (reb-quit)
          (query-replace-regexp re replacement delimited beg end)))))

#+end_src

** Easier accents

At work I sometimes have to write in French. On top of that I'm attempting to learn both French and Spanish. As such I need a nicer way to insert accented characters than Emacs' default =C-x 8= flow.

#+begin_src emacs-lisp

  (use-package accent
    :bind
    ("C-x e" . 'accent-menu))

#+end_src

** Surround

Something I miss still from my Neovim days is the venerable surround
plugin. Since I don't use Evil evil-surround isn't for me. However, someone else
has already had the idea of porting this concept back to vanilla Emacs as
well. The, rather obviously named, =surround= package.

#+begin_src emacs-lisp

  (use-package surround
    :bind-keymap ("M-'" . surround-keymap))

#+end_src

** Miscellaneous Enhancements

Emacs has two similar functions for deleting surrounding white space,
=delete-horizontal-space= which deletes all whitespace surrounding the point on
the current line and =delete-blank-lines= which deletes either blank lines above
and below the current line if it is blank or deletes the current line if it is
blank and the the lines surrounding lines are not. Below is a utility function
to smartly combine the two.

Read up on =cycle-spacing= command. It looks like it might do much of what I'm
doing here.

#+begin_src emacs-lisp

  (defun current-line-empty-p ()
    "Return true is the point is in an empty line, false otherwise."

    (save-excursion
      (beginning-of-line)
      (looking-at-p "[[:blank:]]*$")))

  (defun delete-blank-space-dwim ()
    "Delete surrounding whitespace in do-what-I-mean manner.

  When point is in a blank line invoke (delete-blank-lines).
  When point is in whitespace between non-whitespace invoke (delete-horizontal-space)."

    (interactive)

    (if (current-line-empty-p)
        (delete-blank-lines)
      (delete-horizontal-space)))

  (global-set-key (kbd "M-\\") 'delete-blank-space-dwim)

#+end_src

A couple of quick functions to move lines up/down quickly.

#+begin_src emacs-lisp

  (defun move-line-up ()
    "Move up the current line."
    (interactive)
    (transpose-lines 1)
    (forward-line -2)
    (indent-according-to-mode))

  (defun move-line-down ()
    "Move down the current line."
    (interactive)
    (forward-line 1)
    (transpose-lines 1)
    (forward-line -1)
    (indent-according-to-mode))

  (global-set-key [(super up)]  'move-line-up)
  (global-set-key [(super down)]  'move-line-down)

#+end_src

As probably want to zap up to a character as often as I want to zap the character too. I certainly want to zap up to a character far more often than I want to minimize the frame I'm working in. So commandeer the =C-z= binding for that purpose.

#+begin_src emacs-lisp

  (global-set-key (kbd "C-z") 'zap-up-to-char)

#+end_src

Emacs has given us many DWIM versions of common commands over the years. However, they don't replace the 'old version' by default. DWIM when I use the case change commands.

#+begin_src emacs-lisp

  (global-set-key [remap downcase-word] 'downcase-dwim)
  (global-set-key [remap upcase-word] 'upcase-dwim)
  (global-set-key [remap capitalize-word] 'capitalize-dwim)

#+end_src

Turn on electric-pair-mode

#+begin_src emacs-lisp

  (use-package elec-pair
    :config
    (electric-pair-mode))

#+end_src

** Narrow to indirect

Combine two neat features of Emacs to facilitate a better workflow for editing single files with multiple languages.

Currently unaltered. Found here: [[https://demonastery.org/2013/04/emacs-narrow-to-region-indirect/]]

#+begin_src emacs-lisp

  (defun narrow-to-region-indirect (start end)
    "Restrict editing in this buffer to the current region, indirectly."
    (interactive "r")
    (deactivate-mark)
    (let ((buf (clone-indirect-buffer nil nil)))
      (with-current-buffer buf
        (narrow-to-region start end))
      (switch-to-buffer buf)))

  (keymap-set global-map "C-c '" 'narrow-to-region-indirect)

#+end_src

** Hippie Expand

Seamlessly replace =dabbrev= with =hippie-expand= for fun and profit.

#+begin_src emacs-lisp

  (global-set-key [remap dabbrev-expand] 'hippie-expand)

#+end_src

* Behavioral Enhancements

One of the few big holes in Emacs' basic functionality is its undo system. So I use a drop in replacement.

#+begin_src emacs-lisp

  ;; Clean and straightforward undo/redo
  (use-package undo-fu
    :config
    (setopt undo-fu-allow-undo-in-region t)
    :bind
    ("C-/" . undo-fu-only-undo)
    ("C-M-/" . undo-fu-only-redo))

  ;; Persist undo history across sessions
  (use-package undo-fu-session
    :config
    (setq undo-fu-session-incompatible-files '("/COMMIT_EDITMSG\\'" "/git-rebase-todo\\'"))
    (undo-fu-session-global-mode))

#+end_src

I don't want any bells on thanks

#+begin_src emacs-lisp

  (setq visible-bell nil
        ring-bell-function #'ignore)

#+end_src

Treat manual buffer switching, via =switch-to-buffer=, the same way as programmatic buffer switching. With this set =switch-to-buffer= will obey any display action rules in place. N.B. requires Emacs 27+.

#+begin_src emacs-lisp

  (setq switch-to-buffer-obey-display-actions t)

#+end_src

When I want a terminal I want a real terminal. =vterm= essentially add a 'real' terminal into Emacs via the libvterm library.

#+begin_src emacs-lisp

  (use-package vterm
    :init
    (setq vterm-max-scrollback 10000)
    :bind
    ("C-x !" . projectile-run-vterm))

#+end_src

Make Emacs' already helpful **Help** system even more helpful. In addition to adding the =helpful= package to enhance certain queries set a rule to open help buffer's in a side window.

#+begin_src emacs-lisp

  (use-package helpful
    :bind
    ("C-h f" . #'helpful-callable)
    ("C-c F" . #'helpful-function)
    ("C-h v" . #'helpful-variable)
    ("C-h k" . #'helpful-key)
    ("C-h x" . #'helpful-command)
    ("C-c C-d" . #'helpful-at-point))

  (add-to-list 'display-buffer-alist
               '("\\*Help\\*\\|\\*helpful.*\\*"
                 (display-buffer-in-side-window)
                 (side . right)
                 (slot . 0)
                 (window-width . 80)
                 (window-parameters
                  (no-delete-other-windows . t))))

#+end_src

* Utility Functions

Kill the current frame or exit emacs if the frame in question is the only one. Taken from [[https://github.com/rougier/nano-emacs/issues/128]]. Tweaked to confirm but only when killing the last frame. I've accidentally closed the last frame a few too many times for comfort.

#+begin_src emacs-lisp

  (defun luda/quit-dwim (&optional arg)
  	"If current frame is the last frame kill emacs, else delete it."
  	(interactive "P")

  	(if (> (length (frame-list)) 1)
    		(delete-frame arg)
  		(if (y-or-n-p (format "Are you sure you want to close the last frame?"))
  				(save-buffers-kill-terminal arg)
  			(message "Great, back to what you were doing then."))))

  (global-set-key (kbd "C-x C-c") 'luda/quit-dwim)

#+end_src

When I want to kill a buffer I almost always want to kill the buffer I'm in. Occasionally I don't so remap =C-x k= to =kill-this-buffer= and shift =kill-buffer= to =C-x C-k=

#+begin_src emacs-lisp

  (keymap-set global-map "C-x k" 'kill-current-buffer)
  (keymap-set global-map "C-x C-k" 'kill-buffer)

#+end_src

* Specific Language Support

TreeSitter support covers a fair bit of territory for language support. There are however some gaps that need to be filled.

** CSS

Regular CSS should be covered by the native TreeSitter functionality in tandem with =treesit-auto-mode=. However, I still had this in my config so I'll make it =INACTIVE= and resolve it as part of a cleanup pass.

I also need to figure out what to set up for SCSS as we lean on that heavily at my day job.

#+begin_src emacs-lisp

  (use-package css-mode
    :custom
    (tab-width 2)
    (css-indent-offset 2))

#+end_src

** ERB
:LOGBOOK:
- State "CALENDAR"   from              [2024-02-27 Tue 07:52]
:END:

At my day job we have a primarily Rails codebase. This means we have legacy ERB templates to deal with. These are not covered by TreeSitter but =web-mode= is the next best mode for dealing with many template languages. Currently I basically only use it for ERB templates but it serves as a powerful fallback option when things aren't covered by TreeSitter or a specific language mode that does the job better.

#+begin_src emacs-lisp

  (use-package web-mode
    :mode
    (("\\.erb\\'" . web-mode)
     ("\\.html?\\'" . web-mode)))

#+end_src

** HAML

A Rails codebase also means HAML and Slim templates too. Sadly for my config's dependency graph =web-mode= is designed for template languages that are derived from HTML which HAML is not. So bring in its own mode package.

#+begin_src emacs-lisp

  (use-package haml-mode
    :defer t)

#+end_src

** Javascript/Typescript

=jtsx-mode= is a lightweight mode that piggybacks on Emacs' built in JSX/TSX mode and integrates with =TreeSitter= sprinkling some nice utilities over the native mode(s).

#+begin_src emacs-lisp

  (use-package jtsx
    :mode (("\\.jsx?\\'" . jtsx-jsx-mode)
           ("\\.tsx\\'" . jtsx-tsx-mode)
           ("\\.ts\\'" . jtsx-typescript-mode))
    :custom
    (js-indent-level 2)
    (typescript-ts-mode-indent-offset 2)
    (jtsx-switch-indent-offset 0)
    (jtsx-indent-statement-block-regarding-standalone-parent nil)
    (jtsx-jsx-element-move-allow-step-out t)
    (jtsx-enable-jsx-electric-closing-element t)
    :config
    (apheleia-mode t))

#+end_src

** Ruby

#+begin_src emacs-lisp

  (use-package ruby-ts-mode
    :mode "\\.rb\\'"
    :mode "\\.pryrc\\'"
    :mode "Rakefile\\'"
    :mode "Gemfile\\'"
    :config
    (apheleia-mode t))

#+end_src

** YAML

#+begin_src emacs-lisp

  (use-package yaml-ts-mode
    :mode "\\.y[a]?ml")

#+end_src

* Org Mode

One of the killer apps of Emacs the venerable OrgMode. Even more that the rest of the config the Org stuff is usually in flux. I love it but I've never totally gotten the hang of it can have yet to really settle on a workflow.

Various directory and file locations for use configuring Org.

#+begin_src emacs-lisp

  (setq luda/default-org-directory (expand-file-name "org" luda/local-root))
  (setq luda/sync-org-directory (expand-file-name "Dropbox/org" luda/local-root))
  (setq luda/beorg-directory (expand-file-name "Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org" luda/local-root))

  (setq luda/org-dir
        (if (file-directory-p luda/default-org-directory)
            luda/default-org-directory
          luda/sync-org-directory))

  (setq luda/journal-file (expand-file-name "journal.org" luda/org-dir))
  (setq luda/projects-file (expand-file-name "projects.org" luda/org-dir))
  (setq luda/org-id-locations-file (expand-file-name ".org-id-locations" luda/org-dir))

#+end_src

~Define some custom todo keywords.~ I've been trying for ages to find a ToDo workflow/system that works. While my ADHD brain is great at finding such systems It's rubbish at using them. Currently I'm trying to simplify things and go with a 3+1 list system. Which goes something like this.

+ Calendar: Anything which has a specific date attached to it which isn't today.
+ Short: Anything that needs to be done *today*. N.B. things from the calendar with date of 'today' should move to short list.
+ Long: Everything that doesn't belong on once of the other lists.
+ Wait: A subset of the long list for items which depend on something from someone else.

  Originally I was going to do this with todo states. However upon thinking more about it and readying about some other people's approaches I decided that more typical todo states made more sense and that the 3 list system makes more sense to implement as custom agendas/filters. /That/ version still needs to be implemented.

#+begin_src emacs-lisp

  (setq luda/todo-keywords
        `((sequence
           "TODO(t!)" "ACTIVE(a!)" "WAITING(w!)" "MAYBE(m!)" "|" "DONE(d!)" "OBSOLETE(o!)" "CANCELED(-!)")))

#+end_src

Doct is a spiffy little DSL for defining Org capture templates in a more readable, declarative manner.

#+begin_src emacs-lisp

  (use-package doct
  	;;recommended: defer until calling doct
  	:commands (doct))

#+end_src

Configure Org itself

#+begin_src emacs-lisp

  (use-package org
    :init
    (setq org-export-backends '(ascii md html icalendar latex))
    :config
    (setq org-default-notes-file (expand-file-name "todo.org" luda/org-dir)) ;; Should maybe be inbox
    (setq org-log-done 'time)
    (setq org-log-reschedule 'time)
    (setq org-log-into-drawer t)
    (setq org-startup-truncated nil)
    (setq org-todo-keywords luda/todo-keywords)
    (setq org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
    (setq org-id-locations-file luda/org-id-locations-file)
    (setq org-id-locations-file-relative t)
    (setq org-fontify-whole-heading-line t)
    (setq org-agenda-files `(,luda/org-dir ,luda/beorg-directory))
    (setq org-latex-pdf-process
          '("tectonic %f"))

  	(setq org-capture-templates
  				(doct `(("Projects"
  								 :keys "p" :file ,luda/projects-file
  								 :template ("* %{todo-state} %^{Description}\n:PROPERTIES:\n:Created: %U\n:END:\n\n\n%i\n%a")
  								 :children (("Todo"
  														 :keys "t"
  														 :headline "Tasks"
  														 :todo-state "TODO")
  														("Note"
  														 :keys "n"
  														 :headline "Notes"
  														 :todo-state ""))
  								 )
  								("Journal"
  								 :keys "j"
  								 :type plain
  								 :file ,luda/journal-file
  								 :datetree t
  								 :template ":PROPERTIES\n:Created: %U\n:END:\n\n%?\n%i\n%a"
  								 :empty-lines 1))))

  	;; ;; One of my big uses for Org is my literate config so having elisp as a template is a must
  	(add-to-list 'org-structure-template-alist '("sl" . "src emacs-lisp"))

  	:bind
  	("C-c a" . org-agenda)
  	("C-c c" . org-capture)
  	("C-c l" . org-store-link))

#+end_src

Personal overlay for org mode to 'beautify' it a bit. There are plenty of packages and approaches to this but rather than endlessly customizing a handful of different packages I figured I'd roll my own and take what I liked from different sources.

* Version Control
** Magit

The gold standard of Git interfaces and one of the killer apps for Emacs. No real tweaks yet.

#+begin_src emacs-lisp

  (use-package magit
    :bind
    ("C-M-;" . magit-status))

  (defvar-keymap liminal-vc-branch-map
    :doc "Liminal prefix map for version control branch actions."
    "b" #'magit-checkout
    "c" #'magit-branch-create)

  (defvar-keymap liminal-vc-pull-map
    :doc "Liminal prefix map for version control pull/fetch actions."
    "p" #'magit-pull-from-pushremote
    "u" #'magit-pull-from-upstream
    "e" #'magit-pull-branch)

  (defvar-keymap liminal-vc-file-map
    :doc "Liminal prefix map for version control file actions."
    "r" #'magit-file-rename)

  (defvar-keymap liminal-vc-map
    :doc "Liminal prefix key maps version control operations ."
    "b" liminal-vc-branch-map
    "F" liminal-vc-pull-map
    "f" liminal-vc-file-map)

  (keymap-set global-map "C-x g" liminal-vc-map)

#+end_src

** Ediff

Taken from https://panadestein.github.io/emacsd/ a friendlier =ediff= experience. Basically does two things;

1. Save the current window config on entry and restores it on exit.
2. Sets the ediff config to a sensible, usable presentation with the files side by side and the control panel in the same frame, at the bottom.

#+begin_src emacs-lisp

  (defvar luda/ediff-original-windows nil)

  (defun luda/store-pre-ediff-winconfig ()
    "Stores the window arrangement before opening ediff."
    (setq luda/ediff-original-windows (current-window-configuration)))

  (defun luda/restore-pre-ediff-winconfig ()
    "Resets original window arrangement"
    (set-window-configuration luda/ediff-original-windows))

  (use-package ediff
    :hook ((ediff-before-setup . 'luda/store-pre-ediff-winconfig)
           (ediff-quit . 'luda/restore-pre-ediff-winconfig))
    :config
    (setq ediff-window-setup-function 'ediff-setup-windows-plain)
    (setq ediff-split-window-function 'split-window-horizontally))

#+end_src



