#+TITLE: Esprit Emacs - A Literate Configuration
#+AUTHOR: Luke D. Inglis
#+DATE: 04/2026
#+STARTUP: show2levels indent hidestars
#+PROPERTY: header-args :tangle (let ((org-use-tag-inheritance t)) (if (member "INACTIVE" (org-get-tags))  "no" "lit-init.el"))

* Esprit Emacs - Literate Configuration

While learning Emacs I've tried a lot of different prepackaged 'distros'. Most notably, as an erstwhile (neo)vim user, Doom. After learning enough via that route and additionally deciding to try to give vanilla Emacs a solid try I'm leaving the prepackaged distros behind and building my own configuration.

It won't be 100% from scratch (are they ever?) as I really like the approach of the NΛNO configuration project and have built from that. Over all I aim for a practically minimalist approach.

Naturally my config is built 'on the shoulders of giants' where much more experienced Emacs users have gone before. With the goal of learning in mind I aim to do my best to not put anything in this config unless I understand how it works.

To wit, giants on whose shoulders I stand. In no particular order.

+ [[https://github.com/rememberYou/.emacs.d][Terencio Agozzino]] (=rememberYou=)
+ [[https://github.com/rougier/dotemacs][Nicolas Rougier (rougier) - Author of NANO]]
+ [[https://github.com/daviwil/dotfiles/blob/master/Emacs.org][David Wilson (daviwil) - System Crafter]]

Big thanks to those from whom I have learned. (And copy and pasted from...)

As this config sprouted originally from N. Rougier's I will quote directly part of the preamble to his.

#+BEGIN_QUOTE

This document is a literate configuration for GNU Emacs written in [[https://orgmode.org/][org]] format. It cannot be used directly and needs to be transformed to extract all the different code blocks into a single configuration file. This is done using the [[help:org-babel-tangle][org-babel-tangle]] function that "extract the bodies of all source code blocks from the current file into their own source-specific files". You can try by yourself by typing the sequence: =C-c C-v t= (org-babel-execute-subtree).

#+END_QUOTE

* Notes to self                                                    :INACTIVE:

List of less tasks to do that are more theoretical or investigative than the concrete, actionable items above. N.B. the output of these tasks should include two things, one necessary and one conditional. The necessary item is a note with the result of investigating. The conditional item is a To Do added to the list above if the result of the research is an actionable item.

- [ ] [[Https://github.com/radian-software/prescient.el][Prescient]] - An extra layer of intelligence for completion sorting and filtering
- [ ] [[https://github.com/kickingvegas/casual-dired][Casual Dired]] - A transient window based 'porcelain' for Dired aimed at simplifying the UX.
- [ ] [[https://github.com/alphapapa/activities.el][Activities]] - Package built around the idea of saving files, buffers, and
  other related state defined as an /activity/.

* Header

This will generate a header at the top of the tangled file to indicate it is generated and is not meant to be modified directly.

#+BEGIN_SRC emacs-lisp

  ;;; Esprit Emacs --- A literate configuration -*- lexical-binding: t -*-
  ;;; Copyright (C) 2026 Luke D. Inglis

  ;;; This file is free software; you can redistribute it and/or modify
  ;;; it under the terms of the GNU General Public License as published by
  ;;; the Free Software Foundation; either version 3, or (at your option)
  ;;; any later version.

  ;;; This file is distributed in the hope that it will be useful,
  ;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
  ;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ;;; GNU General Public License for more details.

  ;;; For a full copy of the GNU General Public License
  ;;; see <https://www.gnu.org/licenses/>.

#+END_SRC

* Early Init                                                     :HOOK:OTHER:
:PROPERTIES:
:header-args:emacs-lisp: :tangle ~/code/dotemacs/early-init.el
:END:

The =early-init.el= file is mostly lifted from James Cherti's excellent [[https://github.com/jamescherti/minimal-emacs.d][minimal-emacs.d]] project. I don't particularly want to tie my configuration to someone else's architecture so I choose not to base my config on minimal-emacs.d. Cherti's code and the research behind is are great and I've used much of it without modification.

#+BEGIN_SRC emacs-lisp
  ;;; early-init.el --- Early Init -*- lexical-binding: t; -*-

  ;; Author: Luke Inglis
  ;; URL: https://github.com/ludamillion/esprit-emacs
  ;; Package-Requires: ((emacs "29.1"))
  ;; Keywords: maint
  ;; Version: 0.1.0
  ;; SPDX-License-Identifier: GPL-3.0-or-later
#+END_SRC

** Internal variables

These are variables used only in the =early-init= context.

Naturally a lot of the tuning performed in the =early-init= is done to reduce start up time. We start here by temporarily raising the garbage collection thresholds to prevent unnecessary cleanup during start up.

#+begin_src emacs-lisp
  (defvar esprit-emacs--backup-gc-cons-threshold gc-cons-threshold)
  (defvar esprit-emacs--backup-gc-cons-percentage gc-cons-percentage)

  (setq gc-cons-threshold most-positive-fixnum)
  (setq gc-cons-percentage 1.0)
#+end_src

** Variables

Variables used both in =early-init= and elsewhere in the configuration. Again, this is currently a pared down selection of variables from =minimal-emacs.d=. Most are included with nothing more than their original docstrings. Some additional commentary is added for others.

#+begin_src emacs-lisp
  (defvar esprit-emacs-user-directory "~/code/dotemacs/"
    "Pointer to me Emacs home directory.")
#+end_src

#+begin_src emacs-lisp
  (defvar esprit-emacs-ui-features '()
    "List of user interface features to enable in minimal Emacs setup.
    This variable holds a list of Emacs UI features that can be enabled:
    - context-menu (Enables the context menu in graphical environments.)
    - tool-bar (Enables the tool bar in graphical environments.)
    - menu-bar (Enables the menu bar in graphical environments.)
    - dialogs (Enables both file dialogs and dialog boxes.)
    - tooltips (Enables tooltips.)")

  (defvar esprit-emacs-frame-title-format "%b – Emacs"
    "Template for displaying the title bar of visible and iconified frame.")
#+end_src

This is used throughout the configuration to provide opt-in debugging information and options.

#+begin_src emacs-lisp
  (defvar esprit-emacs-debug (bound-and-true-p init-file-debug)
    "Non-nil to enable debug.")
#+end_src

The following =vars= relate to garbage collection controlling:

1. Whether or not to optimize it
2. How long, in seconds to wait before restoring it to 'normal' state
3. Threshold values to use when GC is in 'normal' state

#+begin_src emacs-lisp
  (defvar esprit-emacs-optimize-startup-gc t
    "If non-nil, increase `gc-cons-threshold' during startup to reduce pauses.
  After Emacs finishes loading, `gc-cons-threshold' is restored to the value
  stored in `esprit-emacs-gc-cons-threshold'.")

  (defvar esprit-emacs-gc-cons-threshold-restore-delay nil
    "Number of seconds to wait before restoring `gc-cons-threshold'.")

  (defvar esprit-emacs-gc-cons-threshold (* 32 1024 1024)
    "Value to which `gc-cons-threshold' is set after Emacs startup.
  Ignored if `esprit-emacs-optimize-startup-gc' is nil.")

  (defvar esprit-emacs-gc-cons-percentage gc-cons-percentage
    "Value to which `gc-cons-percentage' is set after Emacs startup.
  Ignored if `esprit-emacs-optimize-startup-gc' is nil.")
#+end_src

The following are flags controlling optimization of various Emacs behaviors that can negatively affect start up time.

#+begin_src emacs-lisp
  (defvar esprit-emacs-optimize-file-name-handler-alist t
    "Enable optimization of `file-name-handler-alist'.
  When non-nil, this variable activates optimizations to reduce file name handler
  lookups during Emacs startup.")

  (defvar esprit-emacs-disable-mode-line-during-startup t
    "Disable the mode line during startup.
  This reduces visual clutter and slightly enhances startup performance. The
  tradeoff is that the mode line is hidden during the startup phase.")

  (defvar esprit-emacs-package-initialize-and-refresh nil
    "Whether to automatically initialize and refresh packages.
  When set to non-nil, Emacs will automatically call `package-initialize' and
  `package-refresh-contents' to set up and update the package system.")

  (defvar esprit-emacs-inhibit-redisplay-during-startup nil
    "Suppress redisplay during startup to improve performance.
  This prevents visual updates while Emacs initializes. The tradeoff is that you
  won't see the progress or activities during the startup process.")

  (defvar esprit-emacs-inhibit-message-during-startup nil
    "Suppress startup messages for a cleaner experience.
  This slightly enhances performance. The tradeoff is that you won't be informed
  of the progress or any relevant activities during startup.")
#+end_src

** Configuration success guard

While this function is a little more crucial to a 'framework config' such as =minimal-emacs.d= is can still be quite useful when hacking on any config. It add a variable and a post startup check to ensure that we are loading the proper =init.el= and that we haven't indicated any other failure by setting the success flag to false.

#+begin_src emacs-lisp
  (defvar esprit-emacs--success nil)
  (defun esprit-emacs--check-success ()
    "Verify that the Emacs configuration has loaded successfully."
    (unless esprit-emacs--success
      (cond
       ((or (file-exists-p (expand-file-name "~/.emacs.el"))
            (file-exists-p (expand-file-name "~/.emacs")))
        (error "Emacs ignored loading 'init.el'. Please ensure that files such as ~/.emacs or ~/.emacs.el do not exist, as they may be preventing Emacs from loading the 'init.el' file"))

       (t
        (error "Configuration error. Debug by starting Emacs with: --debug-init")))))

  (unless noninteractive
    (add-hook 'emacs-startup-hook #'esprit-emacs--check-success 102))
#+end_src

I usually manage my own themes as their own separate packages but it doesn't hurt to specify a custom theme directory.

#+begin_src emacs-lisp
  (setq custom-theme-directory
        (expand-file-name "themes/" esprit-emacs-user-directory))

  (setq custom-file (expand-file-name "custom.el" esprit-emacs-user-directory))
#+end_src

** Garbage Collection

Garbage collection can cause significant slowdowns during start up. This section delays GC during start up and resets it later.

#+begin_src emacs-lisp
  (defun esprit-emacs--restore-gc-values ()
    "Restore garbage collection values to esprit-emacs.d values."
    (setq gc-cons-threshold esprit-emacs-gc-cons-threshold)
    (setq gc-cons-percentage esprit-emacs-gc-cons-percentage))

  (defun esprit-emacs--restore-gc ()
    "Restore garbage collection settings."
    (if (and (bound-and-true-p esprit-emacs-gc-cons-threshold-restore-delay)
             ;; In noninteractive mode, the event loop does not run
             (not noninteractive))
        ;; Defer garbage collection during initialization to avoid 2 collections.
        (run-with-timer esprit-emacs-gc-cons-threshold-restore-delay nil
                        #'esprit-emacs--restore-gc-values)
      (esprit-emacs--restore-gc-values)))

  (if esprit-emacs-optimize-startup-gc
      ;; `gc-cons-threshold' is managed by esprit-emacs.d
      (add-hook 'emacs-startup-hook #'esprit-emacs--restore-gc 105)
    ;; gc-cons-threshold is not managed by esprit-emacs.d.
    (when (= gc-cons-threshold most-positive-fixnum)
      (setq gc-cons-threshold esprit-emacs--backup-gc-cons-threshold)
      (setq gc-cons-percentage esprit-emacs--backup-gc-cons-percentage)))
#+end_src

** Native compilation and Byte compilation

Tweak some settings related to performing native and byte compilation and tell Emacs we don't care about warnings unless we're in debug mode.

#+begin_src emacs-lisp
  (unless (and (featurep 'native-compile)
               (fboundp 'native-comp-available-p)
               (native-comp-available-p))
    ;; Deactivate the `native-compile' feature if it is not available
    (setq features (delq 'native-compile features)))

  (setq native-comp-warning-on-missing-source esprit-emacs-debug
        native-comp-async-report-warnings-errors (or esprit-emacs-debug 'silent))

  (setq jka-compr-verbose esprit-emacs-debug)
  (setq byte-compile-warnings esprit-emacs-debug
        byte-compile-verbose esprit-emacs-debug)
#+end_src

** Miscellaneous performance tweaks

Tweaks mostly related to changing Emacs defaults and constraints that were established in the mode resource constrained past. On very low spec machines it might be worth reconsidering these.

We live in the future where proper Unicode support is not necessarily universal but can mostly be taken for granted.

#+begin_src emacs-lisp
  (set-language-environment "UTF-8")
#+end_src

Tweak some settings related to file reading

#+begin_src emacs-lisp
  (setq read-process-output-max (* 2 1024 1024))  ; 1024kb
  (setq process-adaptive-read-buffering nil)
#+end_src

Reduce the amount of warning chatter when not concerning with actively debugging the config. Expand the maximum lines of message logging when we are deugging the config.

#+begin_src emacs-lisp
  (setq warning-minimum-level (if esprit-emacs-debug :warning :error))
  (setq warning-suppress-types '((lexical-binding)))

  (when esprit-emacs-debug
    (setq message-log-max 16384))
#+end_src

Don't ping things that look like domain names. (J. Cherti)

#+begin_src emacs-lisp
  (setq ffap-machine-p-known 'reject)
#+end_src

Disable warnings from the legacy advice API. They aren't useful. (J. Cherti)

#+begin_src emacs-lisp
  (setq ad-redefinition-action 'accept)
#+end_src

Font compacting can be very resource-intensive, especially when rendering icon fonts on Windows. This will increase memory usage. (J. Cherti)

#+begin_src emacs-lisp
  (setq inhibit-compacting-font-caches t)
#+end_src

** The rest of it

The following remains to be edited and carved up into meaningful sections. But here it is.

#+begin_src emacs-lisp
  (when (not noninteractive)
    ;; Resizing the Emacs frame can be costly when changing the font. Disable this
    ;; to improve startup times with fonts larger than the system default.
    (setq frame-resize-pixelwise t)

    ;; Without this, Emacs will try to resize itself to a specific column size
    (setq frame-inhibit-implied-resize t)

    ;; A second, case-insensitive pass over `auto-mode-alist' is time wasted.
    ;; No second pass of case-insensitive search over auto-mode-alist.
    (setq auto-mode-case-fold nil)

    ;; Reduce *Message* noise at startup. An empty scratch buffer (or the
    ;; dashboard) is more than enough, and faster to display.
    (setq inhibit-startup-screen t
          inhibit-startup-echo-area-message user-login-name)
    (setq initial-buffer-choice nil
          inhibit-startup-buffer-menu t
          inhibit-x-resources t)

    ;; Disable bidirectional text scanning for a modest performance boost.
    (setq-default bidi-display-reordering 'left-to-right
                  bidi-paragraph-direction 'left-to-right)

    ;; Give up some bidirectional functionality for slightly faster re-display.
    (setq bidi-inhibit-bpa t)

    ;; Remove "For information about GNU Emacs..." message at startup
    (advice-add 'display-startup-echo-area-message :override #'ignore)

    ;; Suppress the vanilla startup screen completely. We've disabled it with
    ;; `inhibit-startup-screen', but it would still initialize anyway.
    (advice-add 'display-startup-screen :override #'ignore)

    (unless esprit-emacs-debug
      ;; Unset command line options irrelevant to the current OS. These options
      ;; are still processed by `command-line-1` but have no effect.
      (unless (eq system-type 'darwin)
        (setq command-line-ns-option-alist nil))
      (unless (memq initial-window-system '(x pgtk))
        (setq command-line-x-option-alist nil))))

  ;;; Performance: File-name-handler-alist

  (defvar esprit-emacs--old-file-name-handler-alist (default-toplevel-value
                                                     'file-name-handler-alist))

  (defun esprit-emacs--respect-file-handlers (fn args-left)
    "Respect file handlers.
  FN is the function and ARGS-LEFT is the same argument as `command-line-1'.
  Emacs processes command-line files very early in startup. These files may
  include special paths like TRAMP paths, so restore `file-name-handler-alist' for
  this stage of initialization."
    (let ((file-name-handler-alist (if args-left
                                       esprit-emacs--old-file-name-handler-alist
                                     file-name-handler-alist)))
      (funcall fn args-left)))

  (defun esprit-emacs--restore-file-name-handler-alist ()
    "Restore `file-name-handler-alist'."
    (set-default-toplevel-value
     'file-name-handler-alist
     ;; Merge instead of overwrite to preserve any changes made since startup.
     (delete-dups (append file-name-handler-alist
                          esprit-emacs--old-file-name-handler-alist))))

  (when (and esprit-emacs-optimize-file-name-handler-alist
             (not esprit-emacs-debug))
    ;; Determine the state of bundled libraries using calc-loaddefs.el. If
    ;; compressed, retain the gzip handler in `file-name-handler-alist`. If
    ;; compiled or neither, omit the gzip handler during startup for improved
    ;; startup and package load time.
    (set-default-toplevel-value
     'file-name-handler-alist
     (if (locate-file-internal "calc-loaddefs.el" load-path)
         nil
       (list (rassq 'jka-compr-handler
                    esprit-emacs--old-file-name-handler-alist))))

    ;; Ensure the new value persists through any current let-binding.
    (put 'file-name-handler-alist 'initial-value
         esprit-emacs--old-file-name-handler-alist)

    ;; Emacs processes command-line files very early in startup. These files may
    ;; include special paths TRAMP. Restore `file-name-handler-alist'.
    (advice-add 'command-line-1 :around #'esprit-emacs--respect-file-handlers)

    (add-hook 'emacs-startup-hook #'esprit-emacs--restore-file-name-handler-alist
              101))

  ;;; Performance: Inhibit redisplay

  (defun esprit-emacs--reset-inhibit-redisplay ()
    "Reset inhibit redisplay."
    (setq-default inhibit-redisplay nil)
    (remove-hook 'post-command-hook #'esprit-emacs--reset-inhibit-redisplay))

  (when (and esprit-emacs-inhibit-redisplay-during-startup
             (not noninteractive)
             (not esprit-emacs-debug))
    ;; Suppress redisplay and redraw during startup to avoid delays and
    ;; prevent flashing an unstyled Emacs frame.
    (setq-default inhibit-redisplay t)
    (add-hook 'post-command-hook #'esprit-emacs--reset-inhibit-redisplay -100))

  ;;; Performance: Inhibit message

  (defun esprit-emacs--reset-inhibit-message ()
    "Reset inhibit message."
    (setq-default inhibit-message nil)
    (remove-hook 'post-command-hook #'esprit-emacs--reset-inhibit-message))

  (when (and esprit-emacs-inhibit-message-during-startup
             (not noninteractive)
             (not esprit-emacs-debug))
    (setq-default inhibit-message t)
    (add-hook 'post-command-hook #'esprit-emacs--reset-inhibit-message -100))

  ;;; Performance: Disable mode-line during startup

  (defvar-local esprit-emacs--hidden-mode-line nil
    "Store the buffer-local value of `mode-line-format' during startup.")

  (when (and esprit-emacs-disable-mode-line-during-startup
             (not noninteractive)
             (not esprit-emacs-debug))
    (put 'mode-line-format
         'initial-value (default-toplevel-value 'mode-line-format))
    (setq-default mode-line-format nil)
    (dolist (buf (buffer-list))
      (with-current-buffer buf
        (when (local-variable-p 'mode-line-format)
          (setq esprit-emacs--hidden-mode-line mode-line-format)
          (setq mode-line-format nil)))))

  ;;; Restore values

  (defun esprit-emacs--startup-load-user-init-file (fn &rest args)
    "Advice to reset `mode-line-format'. FN and ARGS are the function and args."
    (unwind-protect
        ;; Start up as normal
        (apply fn args)
      ;; If we don't undo inhibit-{message, redisplay} and there's an error, we'll
      ;; see nothing but a blank Emacs frame.
      (when esprit-emacs-inhibit-message-during-startup
        (setq-default inhibit-message nil))
      (when esprit-emacs-inhibit-redisplay-during-startup
        (setq-default inhibit-redisplay nil))
      ;; Restore the mode-line
      (when esprit-emacs-disable-mode-line-during-startup
        (unless (default-toplevel-value 'mode-line-format)
          (setq-default mode-line-format (get 'mode-line-format
                                              'initial-value)))
        (dolist (buf (buffer-list))
          (with-current-buffer buf
            (when (local-variable-p 'esprit-emacs--hidden-mode-line)
              (setq mode-line-format esprit-emacs--hidden-mode-line)
              (kill-local-variable 'esprit-emacs--hidden-mode-line)))))))

  (advice-add 'startup--load-user-init-file :around
              #'esprit-emacs--startup-load-user-init-file)

  ;;; UI elements

  (setq frame-title-format esprit-emacs-frame-title-format
        icon-title-format esprit-emacs-frame-title-format)

  ;; Disable startup screens and messages
  (setq inhibit-splash-screen t)

  ;; I intentionally avoid calling `menu-bar-mode', `tool-bar-mode', and
  ;; `scroll-bar-mode' because manipulating frame parameters can trigger or queue
  ;; a superfluous and potentially expensive frame redraw at startup, depending
  ;; on the window system. The variables must also be set to `nil' so users don't
  ;; have to call the functions twice to re-enable them.
  (unless (memq 'menu-bar esprit-emacs-ui-features)
    (push '(menu-bar-lines . 0) default-frame-alist)
    (unless (memq window-system '(mac ns))
      (setq menu-bar-mode nil)))

  (defun esprit-emacs--setup-toolbar (&rest _)
    "Setup the toolbar."
    (when (fboundp 'tool-bar-setup)
      (advice-remove 'tool-bar-setup #'ignore)
      (when (bound-and-true-p tool-bar-mode)
        (funcall 'tool-bar-setup))))

  (unless noninteractive
    (when (fboundp 'tool-bar-setup)
      ;; Temporarily override the tool-bar-setup function to prevent it from
      ;; running during the initial stages of startup
      (advice-add 'tool-bar-setup :override #'ignore)

      (advice-add 'startup--load-user-init-file :after
                  #'esprit-emacs--setup-toolbar)))

  (unless (memq 'tool-bar esprit-emacs-ui-features)
    (push '(tool-bar-lines . 0) default-frame-alist)
    (setq tool-bar-mode nil))

  (setq default-frame-scroll-bars 'right)
  (push '(vertical-scroll-bars) default-frame-alist)
  (push '(horizontal-scroll-bars) default-frame-alist)
  (setq scroll-bar-mode nil)

  (unless (memq 'tooltips esprit-emacs-ui-features)
    (when (bound-and-true-p tooltip-mode)
      (tooltip-mode -1)))

  ;; Disable GUIs because they are inconsistent across systems, desktop
  ;; environments, and themes, and they don't match the look of Emacs.
  (unless (memq 'dialogs esprit-emacs-ui-features)
    (setq use-file-dialog nil)
    (setq use-dialog-box nil))

  ;;; Security
  (setq gnutls-verify-error t)  ; Prompts user if there are certificate issues
  (setq tls-checktrust t)  ; Ensure SSL/TLS connections undergo trust verification
  (setq gnutls-min-prime-bits 3072)  ; Stronger GnuTLS encryption

  ;; This results in a more compact output that emphasizes performance
  (setq use-package-expand-minimally t)

  (setq use-package-minimum-reported-time (if esprit-emacs-debug 0 0.1))
  (setq use-package-verbose esprit-emacs-debug)
  (setq use-package-enable-imenu-support t)

  ;; package.el
  (setq package-enable-at-startup nil)  ; Let the init.el file handle this
  (setq package-archives '(("melpa"        . "https://melpa.org/packages/")
                           ("gnu"          . "https://elpa.gnu.org/packages/")
                           ("nongnu"       . "https://elpa.nongnu.org/nongnu/")
                           ("melpa-stable" . "https://stable.melpa.org/packages/")))
  (setq package-archive-priorities '(("gnu"    . 99)
                                     ("nongnu" . 80)
                                     ("melpa"  . 70)
                                     ("melpa-stable" . 50)))

  (let ((default-directory  (expand-file-name "lisp" user-emacs-directory)))
    (setq load-path
          (append
           (let ((load-path  (copy-sequence load-path))) ;; Shadow
             (append
              (copy-sequence (normal-top-level-add-to-load-path '(".")))
              (normal-top-level-add-subdirs-to-load-path)))
           load-path)))

  ;; Local variables:
  ;; byte-compile-warnings: (not obsolete free-vars)
  ;; End:

  ;;; early-init.el ends here
#+end_src

* Packages management                                              :PERSONAL:

Use [[https://github.com/raxod502/straight.el][straight.el]] for package management and disable checking (for speedup). Hook it up to =use-package= by default at least for the time being.

#+begin_src emacs-lisp
  (unless (featurep 'straight)
    ;; Bootstrap straight.el
    (defvar bootstrap-version)
    (let ((bootstrap-file
           (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
          (bootstrap-version 5))
      (unless (file-exists-p bootstrap-file)
        (with-current-buffer
            (url-retrieve-synchronously
             "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
             'silent 'inhibit-cookies)
          (goto-char (point-max))
          (eval-print-last-sexp)))
      (load bootstrap-file nil 'nomessage)))

  (setopt straight-check-for-modifications nil)
  
#+end_src

Add the =:xdg-state= and =:xdg-cache= keywords to =use-package= helping to keep the the Emacs home directory uncluttered.

#+begin_src emacs-lisp
  (use-package use-package-xdg
    :demand t
    :straight (use-package-xdg :type git
                               :host codeberg
                               :repo "rossabaker/use-package-xdg"))
#+end_src

The =lisp= directory is for utility code/packages that are not mature or complex enough to split out into their own repo.

#+begin_src emacs-lisp
  (add-to-list 'load-path (expand-file-name "lisp/" user-emacs-directory))
#+end_src

* Meta-Configuration

Setup and tooling specifically related to this configuration itself.

** Init message.

Display a message to the *Messages* buffer showing the Emacs init time.

#+begin_src emacs-lisp
  (let ((inhibit-message t))
    (message "Welcome to GNU Emacs / Esprit Edition")
    (message (format "Initialization time: %s" (emacs-init-time))))
#+end_src

** Configuration reload

#+begin_src emacs-lisp
  (defun esprit/reload-init-file ()
    "Reload the file referenced by `user-init-file`."

    (interactive)
    (load-file user-init-file))

  (keymap-global-set "<f5>" 'esprit/reload-init-file)
#+end_src

* Backups Etc.

Various settings related to avoiding unnecessary backup and temp files.

No backup of files under version control

#+begin_src emacs-lisp
  (setq vc-make-backup-files nil)
#+end_src

Don't clobber symlinks

#+begin_src emacs-lisp
  (setq backup-by-copying t)
#+end_src

Version numbers for backup files

#+begin_src emacs-lisp
  (setq version-control t)
#+end_src

Delete excess backup files silently.

#+begin_src emacs-lisp
  (setq delete-old-versions t)
#+end_src

Number of old versions to keep

#+begin_src emacs-lisp
  (setq kept-old-versions 3)
#+end_src

Number of new versions to keep

#+begin_src emacs-lisp
  (setq kept-new-versions 6)
#+end_src

Delete files to trash.

#+begin_src emacs-lisp
  (setq delete-by-moving-to-trash t)
#+end_src
        
More trouble than worth

#+begin_src emacs-lisp
  (setq create-lockfiles nil)
#+end_src
  
Enable and tweak =recentf-mode= to keep track of files recently operated on.

#+begin_src emacs-lisp

  (use-package recentf
    :hook
    (after-init . recentf-mode)
    :custom
    (recentf-max-saved-items 100)
    :xdg-state
    (recentf-save-file "recentf"))

#+end_src

Preserve cursor position per file across sessions.

#+begin_src emacs-lisp

  (use-package saveplace
    :xdg-state
    (save-place-file "saveplace")
    :custom
    (save-place-forget-unreadable-files t))

#+end_src

Auto-save mode can save your behind sometimes. Let's hide them away in a standard location though...

#+begin_src emacs-lisp
  (use-package emacs
    :hook (after-init . auto-save-mode)
    :xdg-state
    (auto-save-list-prefix "saves/"))
#+end_src

Speaking of automatic behaviors; there are no reasons I can think of to not revert (read update) open files when their contents have changed.

#+begin_src emacs-lisp
  (use-package autorevert
    :hook (emacs-startup . #'global-auto-revert-mode))
#+end_src

* History                                                              :HOOK:

Remove text properties for kill ring entries (see https://emacs.stackexchange.com/questions/4187). This saves a lot of time when loading it.

#+begin_src emacs-lisp

  (defun unpropertize-kill-ring ()
    (setq kill-ring (mapcar 'substring-no-properties kill-ring)))

  (add-hook 'kill-emacs-hook 'unpropertize-kill-ring)

#+end_src

We save every possible history we can think of.

#+begin_src emacs-lisp
  (setq savehist-watchlist
        '(bookmark-history
          command-history
          custom-variable-history
          face-name-history
          file-name-history
          minibuffer-history
          query-replace-history
          read-char-history
          read-expression-history
          set-variable-value-history
          kill-ring))

  (use-package savehist
    :hook (after-init . savehist-mode)
    :xdg-state (savehist-file "history")
    :custom
    (kill-ring-max 50)
    (history-length 50)
    (history-delete-duplicates t)
    (savehist-additional-variables savehist-watchlist))
+end_src


* Path

Pull my full set of environmental variables into Emacs. This is most important on MacOS where I am currently spending all of my time.

#+begin_src emacs-lisp
  (use-package exec-path-from-shell
    :if (memq window-system '(mac ns x))
    :custom
    (exec-path-from-shell-variables
     '(
       "PATH"
       "MANPATH"
       "XDG_CONFIG_DIRS"
       "XDG_DATA_DIRS"
       ))
    :config
    (exec-path-from-shell-initialize))
#+end_src

Make Emacs aware of the proper paths for the [[https://asdf-vm.com/][asdf version manager]].

#+begin_src emacs-lisp
  (use-package asdf
    :straight (:type git :host github :repo "tabfugnic/asdf.el")
    :hook (after-init . asdf-enable))
#+end_src

Point to my local root directory. Mostly for the sake of Org later on in the config.

#+begin_src emacs-lisp
  (defvar esprit/local-root "~/"
    "Convenience pointer to my local root directory.")
#+end_src

* MacOS specific settings

Juggle a few modifier keys to make things a little more comfortable.

#+begin_src emacs-lisp

  (when (string-equal system-type "darwin")
    (setq mac-option-modifier 'super)
    (setq mac-command-modifier 'meta))

    #+end_src

* Frame

A variation on =make-frame= that opens to the =*scratch*= buffer rather than the current buffer.

#+begin_src emacs-lisp

  (defun esprit/make-scratch-frame ()
    "Create a new frame and switch to *scratch* buffer."
    (interactive)
    (select-frame (make-frame))
    (switch-to-buffer "*scratch*"))

  (defun esprit/make-eat-frame ()
    "Create a new frame and create an Eat buffer."
    (interactive)
    (select-frame (make-frame))
    (eat-project))

  (defvar-keymap esprit-frame-map
    :doc "Prefix map for frame operations."
    "m" #'make-frame
    "n" #'esprit/make-scratch-frame
    "v" #'esprit/make-eat-frame)

  (keymap-global-set "M-n" esprit-frame-map)

#+end_src

Mini-ontop is a small convenience library to prevent buffer position from jumping around due to an expandable minibuffer.

#+begin_src emacs-lisp
  (use-package mini-ontop
    :straight (:host github :repo "hkjels/mini-ontop.el")
    :hook
    (after-init . mini-ontop-mode))
#+end_src

* Esprit Themes

New theme ideas I'm playing around with using [[https://www.reasonable.work/colors/][Reasonable Colors]].

#+begin_src emacs-lisp
  (use-package esprit-themes
    ;; :straight (:type git :host github :repo "ludamillion/esprit-themes")
    :load-path "~/code/esprit-themes")
#+end_src

* Esprit modeline

My own personal mode-line.

#+begin_src emacs-lisp
  (use-package esprit-line
    :load-path "~/code/esprit-line"
    :hook (after-init esprit-line-mode)
    :custom
    (esprit-line-glyph-alist esprit-line-glyphs-unicode))
#+end_src

* Circadian

I prefer the legibility of a well designed light theme when the lighting is good. However, I don't want to burn my retinas at night. Thankfully =circadian= exists to automatically adjust my theme at sunrise/sunset in my local area.

#+begin_src emacs-lisp

  (use-package circadian
    :straight t
    :custom
    (calendar-latitude 42.4)
    (calendar-longitude -71.0)
    (circadian-themes '((:sunrise . esprit-cerulean-light)
                        (:sunset  . esprit-cerulean-dark)))
    :config
    (circadian-setup))

#+end_src

* Miscellaneous visual settings.

Nicer display of text lines visually.

#+begin_src emacs-lisp

  (setq-default line-spacing 1)
  (global-visual-line-mode)

#+end_src

Always waffle on how minimal to be. Right now line numbers in prog modes are useful enough to allow within my minimal aesthetic. Or maybe not. For now.

#+begin_src emacs-lisp

  (use-package display-line-numbers
    :custom
    (display-line-numbers-widen t)
    :hook
    ((prog-mode conf-mode) . display-line-numbers-mode))

#+end_src

* File handling

I'm almost alway working with files with standardized line endings but on the occasions that I'm not I don't want to automatically convert them.

If I'm going to be working in a context where I want to insert tabs for indentation I'll enable that explicitly. Otherwise we want to keep to indenting with spaces.

#+begin_src emacs-lisp
  (use-package emacs
    :custom
    (inhibit-eol-conversion t)
    (indent-tabs-mode nil))

#+end_src

* PDF

#+begin_src emacs-lisp

  (use-package pdf-tools
    :config
    (pdf-tools-install)
    (setq-default pdf-view-display-size 'fit-width)
    (define-key pdf-view-mode-map (kbd "C-s") 'isearch-forward)
    :custom
    (pdf-annot-activate-created-annotations t "automatically annotate highlights"))

  (add-hook 'pdf-view-mode-hook (lambda() (display-line-numbers-mode -1)))

#+end_src

* Vertico

Building on Emacs own =completing-read= function Vertico provides a minimalist UI for completion in the minibuffer. It can be thought of as a sleeker, more minimalist alternative to [[https://github.com/abo-abo/swiper][Ivy]] or [[https://github.com/emacs-helm/helm][Helm]].

#+begin_src emacs-lisp

  (use-package vertico
    :bind (:map vertico-map
                ("C-<backspace>" . vertico-directory-up))
    :custom
    (vertico-resize t)
    (vertico-multiform-categories ; Choose a multiform
     '((file reverse)
       (consult-location)
       (imenu buffer)
       (library reverse indexed)
       (t reverse)
       ))
    (vertico-multiform-commands
     '(("flyspell-correct-*" grid reverse)
       (org-refile grid reverse indexed)
       (consult-yank-pop indexed)
       (consult-flycheck)
       (consult-lsp-diagnostics)
       ))
    :init
    (vertico-mode))

#+end_src

* Consult

What Vertico is to Ivy [[https://github.com/minad/consult][Consult]] is to Ivy's =counsel-mode=. It provides searchable replacements to many common Emacs commands.

#+begin_src emacs-lisp

  (defun wrapper/consult-ripgrep (&optional dir given-initial)
    "Pass the region to consult-ripgrep if available.

  DIR and GIVEN-INITIAL match the method signature of `consult-wrapper'."
    (interactive "P")
    (let ((initial
           (or given-initial
               (when (use-region-p)
                 (buffer-substring-no-properties (region-beginning) (region-end))))))
      (consult-ripgrep dir initial)))

  (use-package consult
  :straight t
  :hook (after-init . #'consult-mode)
  :bind (("M-s d"     . consult-fd) ;; Requires having fd installed otherwise use consult-find
         ("M-s G"     . consult-git-grep)
         ("M-s r"     . wrapper/consult-ripgrep)
         ("M-s l"     . consult-line)
         ("M-s L"     . consult-line-multi)
         ("M-s k"     . consult-keep-lines)
         ("M-s u"     . consult-focus-lines)
         ("M-s <SPC>" . consult-buffer)
         ("M-y"       . consult-yank-pop)
         ("C-x M-k"   . consult-kmacro)
         ("M-g g"     . consult-goto-line)
         ("M-g i"     . consult-imenu)
         ("M-g o"     . consult-outline)
         ("C-x b"     . consult-bookmark))
  :init
  (advice-add #'register-preview :override #'consult-register-window)
  (setq register-preview-delay 0.5)
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)
  :config
  (setq consult-preview-key "M-.")
  (setq consult-narrow-key "<"))

#+end_src

* Orderless

Orderless enhances completion functions allowing for searching by space delimited terms. The order of these terms does not matter, hence the name.

#+begin_src emacs-lisp

  (use-package orderless
    :straight t
    :custom
    (completion-styles '(orderless partial-completion basic))
    (completion-category-defaults nil)
    (completion-category-overrides '((file (styles partial-completion)))))

#+end_src

* Corfu

Another package from =minad= (author of Vertico and Consult) Corfu is the 'in-buffer completion counterpart' to Vertico. Similarly it provides a minimalist wrapper around native bahaviors to provide an enhanced experience. Corfu hooks into Emacs' native =complete-in-region= and leverages whatever sources are available from =completion-at-point-functions= as sources for completion options.

#+begin_src emacs-lisp

  (defun corfu-x-eshell-hook ()
    "Set up Corfu behaviors in a shell friendly way."
    (setq-local corfu-auto nil)
    (corfu-mode))

  (defun esprit/corfu-modes ()
    "Activate the desired corfu modes."
    (corfu-history-mode)
    (corfu-echo-mode)
    (global-corfu-mode))

  (use-package corfu
    :straight t
    :init
    (setq corfu-cycle t
          corfu-auto t
          corfu-on-exact-match nil)
    :hook
    (after-init . esprit/corfu-modes)
    (eshell-mode . corfu-x-eshell-hook))

#+end_src

* Cape

Yet another package from =minad=. As mentioned Corfu leverages the =completion-at-point-functions= to populate its options. Cape complements it by providing a suite of such functions, usually referred to as Capfs.

#+begin_src emacs-lisp
  (defun esprit/cape-capf-setup-eglot ()
  "Configure cape completion at point functions for Eglot managed modes."
  (let ((result))
    (dolist (element `(,(cape-capf-buster #'eglot-completion-at-point)
		       cape-file
		       cape-dabbrev) result)
      (add-to-list 'completion-at-point-functions element))))

(defun esprit/cape-capf-setup-org ()
  "Configure cape completion at point functions for org mode."
  (let ((result))
    (dolist (element '(cape-dict cape-dabbrev) result)
      (add-to-list 'completion-at-point-functions element))))

(defun esprit/cape-capf-setup-git-commit ()
  "Configure cape completion at point functions for git-commit mode."
  (let ((result))
    (dolist (element '(cape-dict cape-dabbrev) result)
      (add-to-list 'completion-at-point-functions element))))

(use-package cape
  :straight t
  :config
  (setq completion-category-overrides '((eglot (styles orderless))
                                        (eglot-capf (styles orderless))))
  :hook
  ((eglot-managed-mode . esprit/cape-capf-setup-eglot)
   (org-mode . esprit/cape-capf-setup-org)
   (git-commit-mode . esprit/cape-capf-setup-git-commit)))
#+end_src
* Marginalia

Marginalia adds rich annotations to the minibuffer completions. Good for quick reference and discoverability.

#+begin_src emacs-lisp

  (use-package marginalia
    :init
    (marginalia-mode)
    :custom (marginalia--align 'right)
    :bind (:map minibuffer-local-map
                ("M-A" . marginalia-cycle)))

#+end_src

* Embark

#+begin_src emacs-lisp

  (use-package embark
    :straight t
    :bind
    (("C-." . embark-act)         ;; pick some comfortable binding
     ("M-." . embark-dwim)        ;; good alternative: M-.
     ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'
    :init
    ;; Optionally replace the key help with a completing-read interface
    (setq prefix-help-command #'embark-prefix-help-command)
    :config
    ;; Hide the mode line of the Embark live/completions buffers
    (add-to-list 'display-buffer-alist
                 '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                   nil
                   (window-parameters (mode-line-format . none)))))

  (use-package embark-consult
    :straight t
    :after (consult embark)
    :hook
    (embark-collect-mode . consult-preview-at-point-mode))

#+end_src

* Tempel

Another minad package to try. This time template expansion.

#+begin_src emacs-lisp

  (use-package tempel
    ;; Require trigger prefix before template name when completing.
    :custom
    (tempel-trigger-prefix "<")

    :bind (("M-=" . tempel-complete) ;; Alternative tempel-expand
           ("M-*" . tempel-insert))
    :init

    ;; Setup completion at point
    (defun tempel-setup-capf ()
      ;; Add the Tempel Capf to `completion-at-point-functions'.
      ;; `tempel-expand' only triggers on exact matches. Alternatively use
      ;; `tempel-complete' if you want to see all matches, but then you
      ;; should also configure `tempel-trigger-prefix', such that Tempel
      ;; does not trigger too often when you don't expect it. NOTE: We add
      ;; `tempel-expand' *before* the main programming mode Capf, such
      ;; that it will be tried first.
      (setq-local completion-at-point-functions
                  (cons #'tempel-expand
                        completion-at-point-functions)))

    (add-hook 'conf-mode-hook 'tempel-setup-capf)
    (add-hook 'prog-mode-hook 'tempel-setup-capf)
    (add-hook 'text-mode-hook 'tempel-setup-capf))

  ;; Optional: Add tempel-collection.
  ;; The package is young and doesn't have comprehensive coverage.
  (use-package tempel-collection)

#+end_src

* Ace Window

#+begin_src emacs-lisp

  (use-package ace-window
    :bind
    ("M-o" . 'ace-window)
    :config
    (setq aw-keys '(?a ?s ?d ?f ?j ?k ?l)
          aw-dispatch-always t
          aw-dispatch-alist
          '((?x aw-delete-window "Ace - Delete Window")
            (?c aw-swap-window "Ace - Swap Window")
            (?n aw-flip-window)
            (?v aw-split-window-vert "Ace - Split Vert Window")
            (?h aw-split-window-horz "Ace - Split Horz Window")
            (?m delete-other-windows "Ace - Maximize Window")
            (?g delete-other-windows)
            (?b balance-windows)
            (?u (lambda ()
                  (progn
                    (winner-undo)
                    (setq this-command 'winner-undo))))
            (?r winner-redo))))

#+end_src

Not directly related to ace but philosophically related. Key binding for quickly hopping between the current buffer and the last visited one.

#+begin_src emacs-lisp

  (keymap-global-set "C-M-o" 'mode-line-other-buffer)

#+end_src

* Save Visited Files

I've looked around for different types of session management for Emacs. For the
most part I don't want anything more than just remembering the files I had open
if I need to quit out for some reason. Thankfully someone else had the same
idea.

#+begin_src emacs-lisp
  (use-package save-visited-files
    :init
    (save-visited-files-mode t)
    :xdg-state
    (save-visited-files-location "save-visited-files")
    :custom
    (save-visited-files-ignore-tramp-files t)
    (save-visited-files-ignore-directories nil)
    (save-visited-files-auto-restore nil))
#+end_src

* Minibuffer

#+begin_src emacs-lisp

  ;; Add prompt indicator to `completing-read-multiple'.
  ;; We display [CRM<separator>], e.g., [CRM,] if the separator is a comma.
  (defun crm-indicator (args)
    (unless 
        (cons (format "[crm: %s] %s"
  		    (replace-regexp-in-string
  		     "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
  		     crm-separator)
  		    (car args))
  	    (cdr args)))
    (advice-add #'completing-read-multiple :filter-args #'crm-indicator)

    ;; Do not allow the cursor in the minibuffer prompt
    (setq minibuffer-prompt-properties
  	'(read-only t cursor-intangible t face minibuffer-prompt))
    (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)

    ;; Enable recursive minibuffers
    (setq enable-recursive-minibuffers t)

#+end_src

* Modes Meta

Stuff related, at least philosophically to the management of modes themselves.

#+begin_src emacs-lisp
  (defvar-keymap esprit-modes-toggles-map
    :name "esprit-toggles"
    :doc "Esprit prefix key maps | minor mode toggling."
    "v" #'global-visual-line-mode
    "f" #'toggle-frame-fullscreen
    "w" #'whitespace-mode
    "c" #'command-log-mode
    "!" #'flymake-mode)

  (keymap-set global-map "C-x m" esprit-modes-toggle-map)
    #+end_src

* Which key for discoverability

Add which-key for discoverability and because I can only ever remember my most used key bindings.

#+begin_src emacs-lisp

  (use-package which-key
    :config
    (setq which-key-idle-delay 0.75)
    (which-key-mode))

#+end_src

* Projectile

I had stopped exploring projectile for a bit but never removed it. I'm taking a second look now.

#+begin_src emacs-lisp

  (use-package projectile
    :config
    (projectile-mode)
    :custom
    (projectile-project-search-path `(,(concat esprit/local-root "code")))
    :bind (:map projectile-mode-map
  	      ("s-," . projectile-command-map)))

#+end_src

* LSP

Use Eglot for LSP integration. Fewer options than =lsp-mode= but it's built-in and covers the ground that I need it for right noe

#+begin_src emacs-lisp
  (defvar eglot-enabled-modes
    '(js-ts-mode
      typescript-ts-mode
      ruby-mode
      go-ts-mode
      astro-mode)
    "Opt in list of modes which Eglot should manage.")

  (use-package eglot
    :straight (:type built-in)
    :demand t
    :hook (eglot-enabled-modes . eglot-ensure)
    :bind (:map eglot-mode-map
                ("C-x l r" . eglot-rename)
                ("M-k" . eglot-code-actions))
    :custom
    (eldoc-echo-area-use-multiline-p nil)
    (eglot-events-buffer-config '(:size 2000000 :format lisp))
    :config
    (setq-default eglot-workspace-configuration
                  '(:ltex-ls (:language "en-US"
                                        :disabledRules ["MORFOLOGIK_RULE_EN_US"]))))
#+end_src

#+begin_src emacs-lisp

  (use-package eglot-ltex
    :hook
    (text-mode . (lambda ()
  		 (require 'eglot-ltex)
  		 (eglot-ensure)))
    :init
    (setq eglot-ltex-server-path "/usr/local/bin/ltex-ls"))

#+end_src
* Jinx

Fast just-in-time spell checker leveraging the power of the enchant library.

#+begin_src emacs-lisp

  (use-package jinx
    :hook (emacs-startup . global-jinx-mode)
    :bind (("M-$" . jinx-correct)
  	 ("C-M-$" . jinx-languages)))

#+end_src
* Treesitter

I tried the =treesit-auto= package for automagically handling installation and activation of Treesitter parsers/modes but it wasn't working as smoothly as I'd hoped so I'm going to just handle things manually for the time being.

Edit: trying =treesit-auto= yet again as I was unable to get /anything/ to work smoothly/right.

#+begin_src emacs-lisp

  (setq treesit-language-source-alist
        '((css "https://github.com/tree-sitter/tree-sitter-css")
          (lua "https://github.com/MunifTanjim/tree-sitter-lua")
          (ruby "https://github.com/tree-sitter/tree-sitter-ruby")
          (dockerfile "https://github.com/camdencheek/tree-sitter-dockerfile")
          (scss "https://github.com/serenadeai/tree-sitter-scss")
          (elisp "https://github.com/Wilfred/tree-sitter-elisp")
          (go "https://github.com/tree-sitter/tree-sitter-go")
          (html "https://github.com/tree-sitter/tree-sitter-html")
          (json "https://github.com/tree-sitter/tree-sitter-json")
          (make "https://github.com/alemuller/tree-sitter-make")
          (markdown "https://github.com/ikatyang/tree-sitter-markdown")
          (toml "https://github.com/tree-sitter/tree-sitter-toml")
          (yaml "https://github.com/ikatyang/tree-sitter-yaml")))

  (dolist (ts-pair treesit-language-source-alist)
    (let ((language (car ts-pair)) (repo (cadr ts-pair)))
      (unless (treesit-language-available-p language)
        (message "Installing parser for %s from %s" language repo)
        (treesit-install-language-grammar language))))

  (use-package treesit-auto
    :custom
    (treesit-auto-install 'prompt)
    :config
    (global-treesit-auto-mode))

#+end_src

* Formatting

I played around with using Eglot and the LSP for formatting and I might still
do that but it was going to take some configuration to get it to not do
annoying things with the formatting like always using actual tabs and
defaulting to width 8 tabs. Both of those being 'issues' with how the LSP spec
defines tabSize and what Emacs considers a tab and what it considers
indentation.

So for the time being I am using [[https://github.com/radian-software/apheleia][Apheleia]]. Currentinly only set up for Javascript.

#+begin_src emacs-lisp

  (use-package apheleia
    :custom
    ((alist-get 'prettier apheleia-formatters)
     '(npx "prettier" "--print-width" "100" file))
    :config
    (add-to-list 'apheleia-mode-alist '(jsx-mode . prettier))
    (add-to-list 'apheleia-mode-alist '(ruby-ts-mode . rubocop)))

#+end_src

* Avy

Just looking at the tin [[https://github.com/abo-abo/avy][Avy]] is a /...package for jumping to visible text using a char-based decision tree./ However, as Karthik Chikmagalur puts it /Avy can do any thing/.

I'm taking his lead and trying it out as the power tools he makes it out to be.

#+begin_src emacs-lisp

  (defun avy-action-embark (pt)
    (unwind-protect
        (save-excursion
          (goto-char pt)
          (embark-act))
      (select-window
       (cdr (ring-ref avy-ring 0))))
    t)

  (defun avy-action-copy-whole-line (pt)
    (save-excursion
      (goto-char pt)
      (cl-destructuring-bind (start . end)
          (bounds-of-thing-at-point 'line)
        (copy-region-as-kill start end)))
    (select-window
     (cdr
      (ring-ref avy-ring 0)))
    t)

  (defun avy-action-yank-whole-line (pt)
    (avy-action-copy-whole-line pt)
    (save-excursion (yank))
    t)

  (defun avy-action-kill-whole-line (pt)
    (save-excursion
      (goto-char pt)
      (kill-whole-line))
    (select-window
     (cdr
      (ring-ref avy-ring 0)))
    t)

  (defun avy-action-teleport-whole-line (pt)
    (avy-action-kill-whole-line pt)
    (save-excursion (yank)) t)

  (use-package avy
    :straight t
    :bind ("M-j" . avy-goto-char-timer)
    :config
    (setf (alist-get ?. avy-dispatch-alist) 'avy-action-embark
          (alist-get ?k avy-dispatch-alist) 'avy-action-kill-stay
          (alist-get ?K avy-dispatch-alist) 'avy-action-kill-whole-line
          (alist-get ?t avy-dispatch-alist) 'avy-action-teleport
          (alist-get ?T avy-dispatch-alist) 'avy-action-teleport-whole-line
          (alist-get ?y avy-dispatch-alist) 'avy-action-yank
          (alist-get ?w avy-dispatch-alist) 'avy-action-copy
          (alist-get ?W avy-dispatch-alist) 'avy-action-copy-whole-line
          (alist-get ?Y avy-dispatch-alist) 'avy-action-yank-whole-line)))
#+end_src

* Occur

Yet another builtin I'm slowly learning to make the most of.

#+begin_src emacs-lisp

  (use-package occur
    :bind (:map isearch-mode-map ("C-o" . isearch-occur)))

#+end_src

* Regexen + Search and replace
:PROPERTIES:
:ID:       1739F061-BA7D-4A55-AD41-5A5B0FD810C5
:END:

Engaging some power tools to enhance the use of regular expressions in Emacs.

A nice native feature of Emacs is the =re-builder= package which allows you to build regular expressions with interactive feedback. It also allow you to work around some of the more annoying aspects of Emacs' native regular expression syntax. What it doesn't do is hook directly into some of the most common tasks you want regexp for such as =query-replace-regexp=.

The follow is code that is taken from Karthik Chikmagalur's fantastic blog entry on bridging that gap. Found here [[https://karthinks.com/software/bridging-islands-in-emacs-1/][Bridging Islands in Emacs]]

#+begin_src emacs-lisp
  (use-package re-builder
    :bind (("M-s %" . #'re-builder)
           :map reb-mode-map ("RET" . #'reb-replace-regexp)
           :map reb-lisp-mode-map ("RET" . #'reb-replace-regexp))
    :custom
    (reb-re-syntax 'string)
    :config
    (defvar my/re-builder-positions nil
      "Store point and region bounds before calling re-builder")

    (advice-add 're-builder
                :before
                (defun my/re-builder-save-state (&rest _)
                  "Save into `my/re-builder-positions' the point and region
  positions before calling `re-builder'."
                  (setq my/re-builder-positions
                        (cons (point)
                              (when (region-active-p)
                                (list (region-beginning)
                                      (region-end)))))
                  (message "Set positions to: %s" my/re-builder-positions)))

    (defun reb-replace-regexp (&optional delimited)
      "Run `query-replace-regexp' with the contents of re-builder. With
  non-nil optional argument DELIMITED, only replace matches
  surrounded by word boundaries."
      (interactive "P")
      (reb-update-regexp)
      (let* ((re (reb-target-value 'reb-regexp))
             (replacement (query-replace-read-to
                           re
                           (concat "Query replace"
                                   (if current-prefix-arg
                                       (if (eq current-prefix-arg '-) " backward" " word")
                                     "")
                                   " regexp"
                                   (if (with-selected-window reb-target-window
                                         (region-active-p)) " in region" ""))
                           t))
             (pnt (car my/re-builder-positions))
             (beg (cadr my/re-builder-positions))
             (end (caddr my/re-builder-positions)))
        (with-selected-window reb-target-window
          (goto-char pnt) ; replace with (goto-char (match-beginning 0)) if you want
                                          ; to control where in the buffer the replacement starts
                                          ; with re-builder
          (setq my/re-builder-positions nil)
          (reb-quit)
          (query-replace-regexp re replacement delimited beg end)))))

#+end_src

* Easier accents

At work I sometimes have to write in French. On top of that I'm attempting to learn both French and Spanish. As such I need a nicer way to insert accented characters than Emacs' default =C-x 8= flow.

#+begin_src emacs-lisp

  (use-package accent
    :bind
    ("C-x e" . 'accent-menu))

#+end_src

* Surround

Something I miss still from my Neovim days is the venerable surround
plugin. Since I don't use Evil evil-surround isn't for me. However, someone else
has already had the idea of porting this concept back to vanilla Emacs as
well. The, rather obviously named, =surround= package.

#+begin_src emacs-lisp

  (use-package surround
    :bind-keymap ("M-'" . surround-keymap))

#+end_src

* Miscellaneous Enhancements

Emacs has two similar functions for deleting surrounding white space,
=delete-horizontal-space= which deletes all whitespace surrounding the point on
the current line and =delete-blank-lines= which deletes either blank lines above
and below the current line if it is blank or deletes the current line if it is
blank and the the lines surrounding lines are not. Below is a utility function
to smartly combine the two.

N.B. I should read up on =cycle-spacing= command. It looks like it might do much of what I'm doing here.

#+begin_src emacs-lisp

  (defun current-line-empty-p ()
    "Return true is the point is in an empty line, false otherwise."
    (save-excursion
      (beginning-of-line)
      (looking-at-p "[[:blank:]]*$")))

  (defun delete-blank-space-dwim ()
    "Delete surrounding whitespace in do-what-I-mean manner.

  When point is in a blank line invoke (delete-blank-lines).
  When point is in whitespace between non-whitespace invoke (delete-horizontal-space)."
    (interactive)
    (if (current-line-empty-p)
        (delete-blank-lines)
      (delete-horizontal-space)))
  (global-set-key (kbd "M-\\") 'delete-blank-space-dwim)

#+end_src

A couple of quick functions to move lines up/down quickly.

#+begin_src emacs-lisp

  (defun move-line-up ()
    "Move up the current line."
    (interactive)
    (transpose-lines 1)
    (forward-line -2)
    (indent-according-to-mode))

  (defun move-line-down ()
    "Move down the current line."
    (interactive)
    (forward-line 1)
    (transpose-lines 1)
    (forward-line -1)
    (indent-according-to-mode))

  (global-set-key [(super up)]  'move-line-up)
  (global-set-key [(super down)]  'move-line-down)

#+end_src

As probably want to zap up to a character as often as I want to zap the character too. I certainly want to zap up to a character far more often than I want to minimize the frame I'm working in. So commandeer the =C-z= binding for that purpose.

#+begin_src emacs-lisp
  (use-package emacs
    :bind ("C-z" . #'zap-up-to-char))
#+end_src

Emacs has given us many DWIM versions of common commands over the years. However, they don't replace the 'old version' by default. DWIM when I use the case change commands.

#+begin_src emacs-lisp

  (global-set-key [remap downcase-word] 'downcase-dwim)
  (global-set-key [remap upcase-word] 'upcase-dwim)
  (global-set-key [remap capitalize-word] 'capitalize-dwim)

#+end_src

Turn on electric-pair-mode

#+begin_src emacs-lisp
  (use-package elec-pair
    :init (electric-pair-mode))
#+end_src

* Visual line

#+begin_src emacs-lisp
  (use-package emacs
    :hook ((esprit-prose-modes . visual-line-mode)
           (esprit-prose-modes . variable-pitch-mode)))
#+end_src

* Narrow to indirect

Combine two neat features of Emacs to facilitate a better workflow for editing single files with multiple languages.

Currently unaltered. Found here: [[https://demonastery.org/2013/04/emacs-narrow-to-region-indirect/]]

#+begin_src emacs-lisp

  (defun narrow-to-region-indirect (start end)
    "Restrict editing in this buffer to the current region, indirectly."
    (interactive "r")
    (deactivate-mark)
    (let ((buf (clone-indirect-buffer nil nil)))
      (with-current-buffer buf
        (narrow-to-region start end))
      (switch-to-buffer buf)))

  (keymap-set global-map "C-c '" 'narrow-to-region-indirect)

#+end_src

* Hippie Expand

Seamlessly replace =dabbrev= with =hippie-expand= for fun and profit.

#+begin_src emacs-lisp
  (global-set-key [remap dabbrev-expand] 'hippie-expand)
#+end_src

* Join line

#+begin_src emacs-lisp
  (keymap-global-set "C-j" #'join-line)
#+end_src

* Behavioral Enhancements

One of the few big holes in Emacs' basic functionality is its undo system. So I use a drop in replacement.

#+begin_src emacs-lisp
  (use-package undo-fu
    :custom
    (undo-fu-allow-undo-in-region t)
    (undo-limit 67108864) ; 64mb.
    (undo-strong-limit 100663296) ; 96mb.
    (undo-outer-limit 1006632960) ; 960mb.
    :bind
    ("C-/" . undo-fu-only-undo)
    ("C-?" . undo-fu-only-redo))

  ;; Persist undo history across sessions
  (use-package undo-fu-session
    :hook
    (after-init . undo-fu-session-global-mode)
    :xdg-state
    (undo-fu-session-directory "undo-fu-session")
    :custom
    (undo-fu-session-compression 'nil)
    (undo-fu-session-incompatible-files
     '("/COMMIT_EDITMSG\\'" "/git-rebase-todo\\'")))
#+end_src

I don't want any bells on thanks

#+begin_src emacs-lisp

  (setq visible-bell nil
        ring-bell-function #'ignore)

#+end_src

Treat manual buffer switching, via =switch-to-buffer=, the same way as programmatic buffer switching. With this set =switch-to-buffer= will obey any display action rules in place. N.B. requires Emacs 27+.

#+begin_src emacs-lisp
  (setq switch-to-buffer-obey-display-actions t)
#+end_src

When I want a terminal I want a real terminal. =vterm= essentially add a 'real' terminal into Emacs via the libvterm library.

#+begin_src emacs-lisp

  (use-package vterm
    :init
    (setq vterm-max-scrollback 10000)
    :bind
    ("C-x !" . projectile-run-vterm))

#+end_src

Make Emacs' already helpful **Help** system even more helpful.

#+begin_src emacs-lisp
  (defun esprit/helpful-switch-to-buffer (buffer-or-name)
    "Switch to helpful BUFFER-OR-NAME.

  If we're already in a helpful buffer than reuse its window;
  otherwise create a new window."

    (if (eq major-mode 'heplful-mode)
        switch-to-buffer buffer-or-name)
    (pop-to-buffer buffer-or-name))

  (use-package helpful
    :custom
    (helpful-switch-to-buffer #'esprit/helpful-switch-to-buffer)
    :bind
    ("C-h o"    . #'helpful-symbol)
    ("C-h f"    . #'helpful-callable)
    ("C-c F"    . #'helpful-function)
    ("C-h v"    . #'helpful-variable)
    ("C-h k"    . #'helpful-key)
    ("C-h x"    . #'helpful-command)
    ("C-c C-d"  . #'helpful-at-point))
#+end_src

Special mode is /"A special major mode is intended to view specially formatted data rather than files."/. Most practically this means help(ful) buffers and the like. I prefer this kind of informational display to be in a side window.

#+begin_src emacs-lisp
  (add-to-list 'display-buffer-alist
               '((derived-mode special-mode)
                 (display-buffer-in-side-window)
                 (side . right)
                 (slot . 0)
                 (window-width . 80)
                 (window-parameters
                  (no-delete-other-windows . t))))
#+end_src

* Utility Functions

Kill the current frame or exit emacs if the frame in question is the only one. Taken from [[https://github.com/rougier/nano-emacs/issues/128]]. Tweaked to confirm but only when killing the last frame. I've accidentally closed the last frame a few too many times for comfort.

#+begin_src emacs-lisp

  (defun esprit/quit-dwim (&optional arg)
    "If current frame is the last frame kill emacs, else delete it."
    (interactive "P")

    (if (> (length (frame-list)) 1)
        (delete-frame arg)
      (if (y-or-n-p (format "Are you sure you want to close the last frame?"))
  	(save-buffers-kill-terminal arg)
        (message "Great, back to what you were doing then.")))

    (global-set-key (kbd "C-x C-c") 'esprit/quit-dwim)

#+end_src

When I want to kill a buffer I almost always want to kill the buffer I'm in. Occasionally I don't so remap =C-x k= to =kill-this-buffer= and shift =kill-buffer= to =C-x C-k=

#+begin_src emacs-lisp

  (keymap-set global-map "C-x k" 'kill-current-buffer)
  (keymap-set global-map "C-x C-k" 'kill-buffer)

#+end_src

* Org Mode

One of the killer apps of Emacs the venerable OrgMode. Even more that the rest of the config the Org stuff is usually in flux. I love it but I've never totally gotten the hang of it can have yet to really settle on a workflow.

Various directory and file locations for use configuring Org.

#+begin_src emacs-lisp

  (setq esprit/default-org-directory (expand-file-name "org" esprit/local-root))
  (setq esprit/sync-org-directory (expand-file-name "Dropbox/org" esprit/local-root))
  (setq esprit/beorg-directory (expand-file-name "Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org" esprit/local-root))

  (setq esprit/org-dir
        (if (file-directory-p esprit/default-org-directory)
            esprit/default-org-directory
          esprit/sync-org-directory))

  (setq esprit/journal-file (expand-file-name "journal.org" esprit/org-dir))
  (setq esprit/projects-file (expand-file-name "projects.org" esprit/org-dir))
  (setq esprit/org-id-locations-file (expand-file-name ".org-id-locations" esprit/org-dir))

#+end_src

~Define some custom todo keywords.~ I've been trying for ages to find a ToDo workflow/system that works. While my ADHD brain is great at finding such systems It's rubbish at using them. Currently I'm trying to simplify things and go with a 3+1 list system. Which goes something like this.

+ Calendar: Anything which has a specific date attached to it which isn't today.
+ Short: Anything that needs to be done *today*. N.B. things from the calendar with date of 'today' should move to short list.
+ Long: Everything that doesn't belong on once of the other lists.
+ Wait: A subset of the long list for items which depend on something from someone else.

  Originally I was going to do this with todo states. However upon thinking more about it and reading about some other people's approaches I decided that more typical todo states made more sense and that the 3 list system makes more sense to implement as custom agendas/filters. /That/ version still needs to be implemented.

#+begin_src emacs-lisp

  (setq esprit/todo-keywords
        `((sequence
           "TODO(t!)" "ACTIVE(a!)" "WAITING(w!)" "MAYBE(m!)" "|" "DONE(d!)" "OBSOLETE(o!)" "CANCELED(-!)")))

#+end_src

Configure Org itself

#+begin_src emacs-lisp

  (use-package org
    :init
    (setq org-export-backends '(ascii md html icalendar latex))
    :custom
    (setq org-default-notes-file (expand-file-name "todo.org" esprit/org-dir)) ;; Should maybe be inbox
    (org-log-done 'time)
    (org-log-reschedule 'time)
    (org-log-into-drawer t)
    (org-startup-truncated nil)
    (org-todo-keywords esprit/todo-keywords)
    (org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
    (org-id-locations-file esprit/org-id-locations-file)
    (org-id-locations-file-relative t)
    (org-fontify-whole-heading-line t)
    (org-agenda-files `(,esprit/org-dir ,esprit/beorg-directory))
    (org-latex-pdf-process '("tectonic %f"))
    (org-capture-templates
     '(("f" "Fleeting note" item
        (file+headline org-default-notes-file "Notes")
        "- %?")
       ("p" "Permanent note" plain
        (file denote-last-path)
        #'denote-org-capture
        :no-save t
        :immediate-finish nil
        :kill-buffer t
        :jump-to-captured t)
       ("t" "New task" entry
        (file+headline org-default-notes-file "Tasks")
        "* TODO %i%?")))
    :bind
    ("C-c a" . org-agenda)
    ("C-c c" . org-capture)
    ("C-c l" . org-store-link))

  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (shell . t)))
#+end_src

Add denote for notes.

#+begin_src emacs-lisp
  (use-package denote
    :init
    (denote-rename-buffer-mode 1)
    :custom
    (denote-directory esprit/notes-directory)
    :hook
    (dired-mode . denote-dired-mode)
    :custom-face
    (denote-faces-link ((t (:slant italic)))))

  ;; Denote extensions
  (use-package consult-notes
    :bind
    ("M-s n" . #'consult-notes)
    :commands (consult-notes
               consult-notes-search-in-all-notes)
    :custom
    (consult-notes-file-dir-sources
     `(("Denote" ?d ,esprit/notes-directory))))
#+end_src

* Miscellaneous

Last bits from my (soon to be?) old init.

#+begin_src emacs-lisp
  (use-package emacs-lock
    :config
    (with-current-buffer "*scratch*"
      (emacs-lock-mode 'kill)))

  (use-package wgrep
    :straight t
    :custom
    (wgrep-auto-save-buffer t))

  (use-package combobulate
    :custom
    ;; You can customize Combobulate's key prefix here.
    ;; Note that you may have to restart Emacs for this to take effect!
    (combobulate-key-prefix "C-c o")
    :hook
    ((prog-mode . combobulate-mode)))

  (use-package esprit-movement
    :straight nil
    :bind ("C-a" . #'esprit/beginning-of-line))



#+end_src

* Magit

The gold standard of Git interfaces and one of the killer apps for Emacs. No real tweaks yet.

#+begin_src emacs-lisp

  (use-package magit
    :bind
    ("C-M-;" . magit-status))

  (defvar-keymap esprit-vc-branch-map
    :doc "Esprit prefix map for version control branch actions."
    "b" #'magit-checkout
    "c" #'magit-branch-create)

  (defvar-keymap esprit-vc-pull-map
    :doc "Esprit prefix map for version control pull/fetch actions."
    "p" #'magit-pull-from-pushremote
    "u" #'magit-pull-from-upstream
    "e" #'magit-pull-branch)

  (defvar-keymap esprit-vc-file-map
    :doc "Esprit prefix map for version control file actions."
    "r" #'magit-file-rename)

  (defvar-keymap esprit-vc-map
    :doc "Esprit prefix key maps version control operations ."
    "b" esprit-vc-branch-map
    "F" esprit-vc-pull-map
    "f" esprit-vc-file-map)

  (keymap-set global-map "C-x g" liminal-vc-map)

#+end_src

* Ediff

Taken from https://panadestein.github.io/emacsd/ a friendlier =ediff= experience. Basically does two things;

1. Save the current window config on entry and restores it on exit.
2. Sets the ediff config to a sensible, usable presentation with the files side by side and the control panel in the same frame, at the bottom.

#+begin_src emacs-lisp

  (defvar esprit/ediff-original-windows nil)

  (defun esprit/store-pre-ediff-winconfig ()
    "Stores the window arrangement before opening ediff."
    (setq esprit/ediff-original-windows (current-window-configuration)))

  (defun esprit/restore-pre-ediff-winconfig ()
    "Resets original window arrangement"
    (set-window-configuration esprit/ediff-original-windows))

  (use-package ediff
    :hook ((ediff-before-setup . 'esprit/store-pre-ediff-winconfig)
           (ediff-quit . 'esprit/restore-pre-ediff-winconfig))
    :config
    (setq ediff-window-setup-function 'ediff-setup-windows-plain)
    (setq ediff-split-window-function 'split-window-horizontally))

#+end_src

#+begin_src emacs-lisp
  (provide 'init)
#+end_src
* Prose modes

This is the list of mode I consider prose modes. Modes that focus on the written word rather than code, structured data, &c. Necessary since not all modes that I would consider prose are derived from =text-mode=.

#+begin_src emacs-lisp
  (defvar esprit-prose-modes
    '(
      bibtex-mode
      context-mode
      git-commit-elisp-text-mode
      latex-mode
      markdown-mode
      org-mode
      rst-mode
      text-mode
      )
    "List of which modes esprit considers prose.")
#+end_src

* EditorConfig

Emacs has built in support for =editorconfig= files. If a project uses that I sure as heck want to be using it too. Well...with the limitation that in my experience it's really only code bases that leverage =.editorconfig= files so only load it for prog modes.

#+begin_src emacs-lisp
  (use-package editorconfig
    :hook (prog-mode . editorconfig-mode))
#+end_src

* Dired

Settings an customizations for /Dired/.

#+begin_src emacs-lisp
  (use-package dired
    :straight (:type built-in)
    :custom
    (dired-dwim-target t))
#+end_src

MacOS doesn't use GNU =coreutils= and as such does not include the standard =ls= command which dired expects.

#+begin_src emacs-lisp
  (when (string-equal system-type "darwin")
    (setq dired-use-ls-dired nil))
#+end_src
* Bookmarks

One of the many Emacs features I'm still trying to adopt more fully.

#+begin_src emacs-lisp
  (use-package bookmark
    :straight (:type built-in)
    :commands (bookmark-set)
    :xdg-state
    (bookmark-default-file "bookmarks.eld"))
#+end_src

* Flymake

I have briefly dipped my toes in into =Flycheck= as it is often touted as being supperior to =Flymake= but I'll keep following my own maxim of only adding tools when I determine a need for them. Right now I do not have a particular answer for why /I/ should use Flycheck over Flymake.

#+begin_src emacs-lisp
  (use-package flymake
    :bind (("C-c ! d" . flymake-show-buffer-diagnostics) ; Emacs28
           ("C-c ! D" . flymake-show-project-diagnostics) ; Emacs28
           ("M-]" . flymake-goto-next-error)
           ("M-[" . flymake-goto-prev-error))
    :custom
    (flymake-suppress-zero-counters t)
    (flymake-no-changes-timeout nil)
    (flymake-mode-line-format
     '("" flymake-mode-line-exception flymake-mode-line-counters))
    (flymake-mode-line-counter-format
     '("" flymake-mode-line-error-counter
       flymake-mode-line-warning-counter
       flymake-mode-line-note-counter "")))
#+end_src

* LTex

A languagetools language server.

#+begin_src emacs-lisp
  (defun require-and-ensure-eglot-ltex ()
    "Require the eglot-ltex package and run `eglot-ensure'."
    (require 'eglot-ltex)
    (eglot-ensure))

  (use-package eglot-ltex
    :straight (:host github :repo "emacs-languagetool/eglot-ltex")
    :hook
    (esprit/prose-mode-list . require-and-ensure-eglot-ltex)
    :init
    (setq eglot-ltex-server-path "~/tools/ltex-ls-plus/bin/ltex-ls-plus"
  	eglot-ltex-communication-channel 'stdio))
#+end_src
* Accent

#+begin_src emacs-lisp
  (use-package accent
    :straight t
    :bind ("C-x '" . #'accent-menu))
#+end_src

* Multiple Cursors

#+begin_src emacs-lisp
  (use-package multiple-cursors
    :hook (emacs-startup . multiple-cursors-mode)
    :straight t
    :bind
    ("C->" . #'mc/mark-next-like-this)
    ("C-<" . #'mc/mark-previous-like-this)
    ("C-c C->" . #'mc/mark-all-like-this)
    ("C-S-c C-S-c" . #'mc/edit-lines))
#+end_src
* Swiss Move

#+begin_src emacs-lisp
  (use-package swiss-move
    :bind (("s-n" . swiss-move-line-down)
  	 ("s-p" . swiss-move-line-up)))
#+end_src
* Fontaine

#+begin_src emacs-lisp
  (use-package fontaine
    :straight t
    :demand t
    :xdg-state
    (fontaine-latest-state-file "fontaine-latest-state.eld")
    :custom
    (fontaine-presets
     '((small
        :default-family "Geist Mono"
        :default-height 80
        :variable-pitch-family "Geist")
       (regular) ; like this it uses all the fallback values and is named `regular'
       (medium :default-height 140 :bold-weight regular)
       (laptop  :inherit medium :default-height 140)
       (desktop :inherit medium :default-height 160)
       (large   :inherit medium :default-height 180)
       (t
        :default-family "Geist Mono"
        :variable-pitch-family "Geist"
        :fixed-pitch-height 1.0
        :fixed-pitch-serif-height 1.0
        :variable-pitch-height 1.0)))
    :config
    (fontaine-set-preset (or (fontaine-restore-latest-preset) 'regular))
    ;; Persist the latest font preset when closing/starting Emacs and
    ;; while switching between themes.
    (fontaine-mode 1)
    :bind
    ("C-c f" . #'fontaine-set-preset))
#+end_src
